### ISSUE TITLE
Aliasing 'Link' field causes error

### ISSUE THREAD

**Issue by ryanditjia** [prismicio/prismic-gatsby#133]
This query works okay:

```graphql
query GoogleMapsLinkQuery {
  prismicCompanyMetadata {
    data {
      google_maps_link {
        url
      }
    }
  }
}
```

But aliasing `google_maps_link` results in error:

```graphql
query GoogleMapsLinkQuery {
  prismicCompanyMetadata {
    data {
      googleMapsLink: google_maps_link {
        url
      }
    }
  }
}
```

The error is as follows:

```json
{
  "errors": [
    {
      "message": "Cannot read property 'type' of undefined",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "prismicCompanyMetadata",
        "data",
        "googleMapsLink"
      ],
      "stack": [
        "TypeError: Cannot read property 'type' of undefined",
        "    at type (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/gatsby-source-prismic/src/node/generateTypeDefsForCustomType.js:98:41)",
        "    at resolveFieldValueOrError (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:467:18)",
        "    at resolveField (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:434:16)",
        "    at executeFields (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValueCatchingError (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:495:19)",
        "    at resolveField (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:435:10)",
        "    at executeFields (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:591:12)",
        "    at /Users/ryanditjia/Workspace/unggulsemesta.com/node_modules/graphql/execution/execute.js:492:16",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
      ]
    }
  ],
  "data": {
    "prismicCompanyMetadata": {
      "data": {
        "googleMapsLink": null
      }
    }
  }
}
```

I’m on v3.0.0-beta.10, not sure if the same problem is in v2. Thanks.

**Comment by zpthree** [comment]
I'm running into the same issue. I'm on v3.0.0-beta.9.

**Comment by AllanPooley** [comment]
Hey Angelo, I'd love to migrate some existing sites to v3 - particularly because of schema support. But refactoring fields I've aliased and plucked down as a props would be a nightmare. How complicated is this to fix?

**Comment by angeloashmore** [comment]
Hi @AllanPooley, I don't think the issue is too complicated, but I am not sure how to reference alias information within a GraphQL resolver.

The relevant code is here: https://github.com/angeloashmore/gatsby-source-prismic/blob/dacaaaa5c8483675e0c0cc15be7fd1069bc52432/src/node/generateTypeDefsForCustomType.js#L87-L103

Basically, the resolver checks the key of the field and grabs that value from the parent. Because the field is aliased, the name of the key doesn't match what the parent actually contains.

This was written before the most recent improvements to Gatsby's schema customization, so there may be an alternative way to handle this here: https://www.gatsbyjs.org/docs/schema-customization/#foreign-key-fields

If you have time, I'd be happy to review a PR to fix this!

**Comment by angeloashmore** [comment]
Looking more closely at the example provided, it could be as simple as checking first if `value` exists before running `getNodeById`. That may just band-aid the issue so this requires a bit more thought.

**Comment by mduecker** [comment]
Just ran into the same problem with using aliases.

When I try to use an alias for an image field I get the following error
> "TypeError: Cannot read property 'localFile' of undefined"

In my case I want to fetch the same image twice, with different transformations applied to it. To do this I need to use an alias.

**Comment by angeloashmore** [comment]
@mduecker Glad you found a workaround. We'll definitely need to find a real solution to this. I should have time soon to dive into this.
