### ISSUE TITLE
Using redux instead of window.__PRISMIC_PREVIEW_DATA__  

### ISSUE THREAD

**Issue by chapster11** [prismicio/prismic-gatsby#158]
Anyone run into a mutation issue when using redux to store previewData. 
When I connect my preview component to my redux store and dispatch the previewData i'm getting the below mutation waring.

```
  useEffect(() => {
    if (previewData && path) {
      setPreviewData([...previewData]);
      navigate(path);
    }
  }, [previewData, path]);
```

setPreviewData is my action.
 
> Uncaught Invariant Violation: A state mutation was detected between dispatches, in the path `prismicPreview.data.0.prismicPageTemplate.data.body.0`

Looks like it conflicting with other reducers I use through the site and causing a mutation.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!

The latest plugin, `gatsby-plugin-prismic-previews`, does away with needing to manually manage preview data.
