### ISSUE TITLE
Linked urls showing undefined in Preview. 

### ISSUE THREAD

**Issue by chapster11** [prismicio/prismic-gatsby#164]
I'm having an issue with Prismic link fields showing undefined for urls in preview. They work fine if I choose **link to web** but if I do a **link to Document** then my mergedPreviewData comes in with the url undefined. 

Example of button_url filed not using preview. 
`button_url: {url: "#enroll"}`

Example of button_url filed using preview. The merged data now looks like this.

```
button_url: {
  document: {id: "6dd3da54641-53e4-a3ca56456d780", uid: "hashtag-enroll", type: 
  "page_slug", href: "blabla....", tags: Array(0), …}
  id: "PPFcXmdfghgASDZ_D"
  isBroken: false
  lang: "en-us"
  link_type: "Document"
  raw: {id: "PPFcXmdfghgASDZ_D", type: "page_slug", tags: Array(0), slug: "hashtag-enroll", lang: 
  "en-us", …}
  slug: "hashtag-enroll"
  tags: []
  type: "page_slug"
  uid: "hashtag-enroll"
  url: undefined
}
```

A lot of my links and buttons rely on a url. If there is not one it doesn't render. So in Preview that means nothing renders. How can I get the url when in Preview.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!
