### ISSUE TITLE
v3: Issues with limiting images by height

### ISSUE THREAD

**Issue by rubas** [prismicio/prismic-gatsby#183]
The moment you want to use `maxHeight` with fluid or even fixed Images, you run into annoying issues with the `width` of the html element.

This is closely relates to https://github.com/gatsbyjs/gatsby/pull/17006.

## Graphql
```
 image {
fixed(height: 40) {
  ...GatsbyPrismicImageFixed
}
```

## React
```
import Img from "gatsby-image"
...
<Img fixed={ image } as FixedObject}  />
```
## HTML 
```
<div class=" gatsby-image-wrapper" 
style="position: relative; overflow: hidden; display: inline-block; 
width: 400px; height: 40px;">
   <img src="..." alt="" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; object-fit: cover; object-position: center center; opacity: 0; transition-delay: 500ms;">
    <picture>
```
The problem is that `div` wrapper uses the wrong with (`width: 400px; height: 40px;"` ) - coming from the srcSet breaktpoint and not the size of the image.

# Solution
With gatsby-image-sharp we have `presentationWidth` and `presentationHeight`.

```
childImageSharp {
   fluid(maxHeight: 150) {
    presentationWidth,
    presentationHeight,
    ...GatsbyImageSharpFluid
  }
}
```
This allows is to use it as a fix and have `<Img fixed={ image } as FixedObject}  style={{ width: image.presentationWidth, heigh:image.presentationHeight}}/>`.

We should add those values with the source-plugin as well to handle this issue. You find there code [here](https://github.com/gatsbyjs/gatsby/blob/d6c2b7367a85394284cf20e2b52bcbf9d0156331/packages/gatsby-plugin-sharp/src/index.js#L335).

### Current workaround 
Run the images through Sharp instead of Imgix 😞

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!

The latest version of the plugin uses `@imgix/gatsby` for Imgix images. If this is still a problem, I can take a look at the Imgix plugin.
