### ISSUE TITLE
Preview unpublished docs and normalizePreviewData

### ISSUE THREAD

**Issue by chapster11** [prismicio/prismic-gatsby#197]
I'm having an issue with the data coming back from usePrismicPreview in unpublished documents.
gatsby-source-plugin [unpublished](https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/docs/previews.md#Previewing-un-published-pages) docs says to spread your props that come back from prismic into the component itself. But it doesn't talk about how to deal with the normalizing of the PreviewData

I can't use a template page with the graphql that gets passed into my page component because those get generated by gatsby-node.js. If I try to use the template with the graphql in the template it does not return page object like it would if it was built using gatsby-node createPages method.
```
export const query = graphql`
  query pageQuery($uid: String!) {
    page: prismicPageTemplate(uid: { eq: $uid }) {
    .............
  }
}
```

So I'm using the page component itself but because that has no data shape now how does the following happen for preview unpublished documents

Sample of raw data from unpublished previewData.  
```
step: [
  0: {type: "heading3", text: "Link", spans: Array(0)}
  1: {type: "paragraph", text: "This is some sub text", spans: Array(0)}
]

```
This is how the data would look if I was getting it from mergePrismicPreviewData if it was published preview data.
```
items: [
0 : step:
  html: "<h3>Link</h3><p class="prismic-inheritor"><span>This is some sub text</span></p>"
  text: "Link Connect your Hertz and CLEAR accounts"
  raw: (2) [{…}, {…}]
]
```

I can see for published previews mergePrismicPreviewData and normalizePreviewData is doing the html props for us but how would this work for unpublished pages as we don't have the same shape as what is generated at build time ?  in fact all we have is a component with the dataRaw object when previewing unpublished documents from Prismic.

Sorry for all the edits..

**Comment by angeloashmore** [comment]
Hi @chapster11, unpublished documents are treated the same as published documents. As long as you are providing a schema for the document's type in `gatsby-config.js`, the `usePrismicPreview` hook will return data that is transformed just like in Gatsby.

I'm having trouble understanding the trouble you're experiencing with `gatsby-node.js` and templates. Are you creating pages with `createPage` and passing the UID in context? That's how I typically use Gatsby with Prismic, as well, so this shouldn't be the root of the issue.

Could you run through the guide one more time to ensure everything you have is up to date? The guide has been revised a bit so the process of integrating previews should be a bit simpler.

https://github.com/angeloashmore/gatsby-source-prismic/blob/master/docs/previews-guide.md

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!
