### ISSUE TITLE
Add plugin option for prismic.io address

### ISSUE THREAD

**Issue by dturkington49** [prismicio/prismic-gatsby#258]
When standing up automated testing for my Gatsby project, I need to mock a Prismic instance using mockserver (for example). In order to do this, I need a plugin option which allows the full path of the Prismic repository to be configured. This could be done via an additional plugin option. This option could be used instead of repositoryName and would control the full path (instead of hardcoding https://${repositoryName}.prismic.io). This would enable a mock Prismic service to be stood up at a local address and tested against.

**Comment by angeloashmore** [comment]
@dturkington49 I could see this being useful for your use-case as well as those implementing a proxy server that relays API requests (such as to hide their access token).

Until something like this is implemented, are you able to mock your tests against the real Prismic API URLs? I.e. intercept network requests to `https://${repositoryName}.prismic.io` and route to your mock server.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. The current version of the plugin allows this using the `apiEndpoint` plugin option ([details here](https://prismic.io/docs/technologies/install-the-plugin-gatsby#3.-configure-the-plugin)).
