### ISSUE TITLE
Unable to Preview pages, returns preview resolver

### ISSUE THREAD

**Issue by jpeet86** [prismicio/prismic-gatsby#263]
I have tried setting up Previews using these steps https://github.com/angeloashmore/gatsby-source-prismic/blob/master/docs/previews.md

However, when triggering the preview resolver page it simply returns the Loading paragraph and not a preview of the updated content.

Is there a way to debug this issue?

Files for reference:

**Dependancies**
``` "gatsby": "^2.9.6",
    "gatsby-image": "^2.1.4",
    "gatsby-plugin-manifest": "^2.1.1",
    "gatsby-plugin-offline": "^2.1.3",
    "gatsby-plugin-react-helmet": "^3.0.12",
    "gatsby-plugin-sass": "^2.1.2",
    "gatsby-plugin-sharp": "^2.2.12",
    "gatsby-source-filesystem": "^2.1.20",
    "gatsby-source-prismic": "^3.1.4",
    "gatsby-transformer-sharp": "^2.2.6",
    "prismic-reactjs": "^1.0.0",
```

**gatsby-config.js**
``` options: {
                repositoryName: 'XXX',
                accessToken: `MC5YU2lma2hFQUFDUUFHd1V5.XXX`,
                linkResolver: ({ node, key, value }) => post => `/${post.uid}`,
                fetchLinks: [],
                htmlSerializer: ({ node, key, value }) => (
                    type,
                    element,
                    content,
                    children,
                ) => {},
                schemas: {
                    page_template: require('./src/schemas/page_template.json'),
                    home_page: require('./src/schemas/home_page.json'),
                },
                lang: '*',
            },
```

**gatsby-node.js**
```exports.createPages = async ({ graphql, actions }) => {
    const { createPage } = actions;

    const pages = await graphql(`
    {
        allPrismicPageTemplate {
            edges {
                node {
                    id
                    uid
                }
            }
        }
    }
    `);

    const pageTemplates = {
        Page: path.resolve('./src/templates/page.js'),
    };

    pages.data.allPrismicPageTemplate.edges.forEach(edge => {
        createPage({
            path: `/${edge.node.uid}`,
            component: pageTemplates.Page,
            context: {
                uid: edge.node.uid,
            },
        })
    });
}
```

**Comment by angeloashmore** [comment]
Hi @jpeet86,

The preview resolver page should be redirecting you to the previewed document's page. If it's staying on the preview resolver page, either an error is occurring or `withPreviewResolver` is missing some configuration.

1. Could you check your console on the preview resolver page? You may see errors that that are preventing the redirect from happening.

2. If no errors are printed, check the values of the props added by `withPreviewResolver`. You should have `isPreview` and `isLoading` that will tell you some basic information.

**Comment by griable** [comment]
> Hi there,
> 
> I also gave it a try and stumbled upon what seems to be the same issue.
> 
> My template and case is a really basic prototype, I didn't even set a layout to lower the complexity and be as close as possible from the preview docs but get stuck on the preview page.
> 
> Here are the logs I'm getting in case it can help :
> <img alt="Screenshot 2020-09-01 at 15 24 10" width="1107" src="https://user-images.githubusercontent.com/193908/91857039-a018fc00-ec67-11ea-9c20-eec1969ba5d2.png">

**Comment by griable** [comment]
I still didn't get it to work but I identified two problems in my code:

- I was importing ```import { PageTemplate } from '../templates/PageTemplate'``` instead of ```import PageTemplate from '../templates/PageTemplate'```: I'm using default export in the template and not named in my case
- My linkResolver wasn't "curried", it has to be a function that returns a function as specified in the docs ```({ node, key, value }) => (doc) => { ... }```

@jpeet86 hope this helps

**Comment by greatwitenorth** [comment]
Looks like I tracked down the issue. My linkResolver in gatstby-config.js was depnding on the `link_type` property to know how to render the link based on the type:

```js
linkResolver: ({ node, key, value }) => (doc) => {
          // Your link resolver
          if(doc.link_type === 'Document'){
            const prefix = typeof doc.data !== 'undefined' ? doc.data.slug_prefix + '/' : '';
            
            return '/' + prefix + doc.uid
          }
        }
```

The link resolver used by `withPreviewResolver` does not contain that property so my function was always returning nothing.

I removed the conditional check and it's redirecting properly now:

```js
export default withPreviewResolver(PreviewPage, {
  repositoryName: 'my-repo-name',
  linkResolver: ({ node, key, value }) => (doc) => {
    // Your link resolver
      const prefix = typeof doc.data !== 'undefined' ? doc.data.slug_prefix + '/' : '';
      console.log(doc)
      return '/' + prefix + doc.uid
  },
  fetchLinks: [
    'page.slug_prefix'
  ],
})
```

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!
