### ISSUE TITLE
Add custom fields to Prismic generated node with onCreateNode  

### ISSUE THREAD

**Issue by AdamBelakovics** [prismicio/prismic-gatsby#265]
Hi, I encountered the following problem using gatsby-source-prismic:

I have a simple blog site, and I want to have custom generated human-readable urls, slugs for the blog entries. 

For that I figured the best approach would be similar to [this](https://www.gatsbyjs.com/docs/creating-slugs-for-pages/).

But for some reason it doesn't work, when I query gatsby's API in my templates.

I have a simple NewsItem type and instances in Prismic, which represents a blog entry.

**gatsby-node.js**
```
exports.onCreateNode = ({ node, actions }) => {
  const { createNodeField } = actions;
  if (node.internal.type === "PrismicNewsitem") {
    const slug = slugify(node.data.title.text, {
      lower: true,
      remove: /[*+~.()'"!:@]/g,
    });

    createNodeField({
      node,
      name: "slug",
      value: slug,
    });
  }
};

exports.createPages = () => {
  Creating pages... 
}
```

After running Gatsby dev server `createNodeField` outputs the following for each NewsItem entry:

```
{
  node: {
    path: '/dev-404-page/',
    id: 'SitePage /dev-404-page/',
    parent: null,
    children: [],
    internal: {
      type: 'SitePage',
      contentDigest: 'dfef0fff8c14f741676d67cf456399fb',
      counter: 1,
      owner: 'internal-data-bridge'
    }
  },
  traceId: 'initial-sourceNodes',
  parentSpan: Span {},
  traceTags: { nodeId: 'SitePage /dev-404-page/', nodeType: 'SitePage' },
  activity: undefined,
  type: 'ADD_FIELD_TO_NODE',
  plugin: {
    resolve: '/home/adam/Dev/MyBlog',
    id: '7374ebf2-d961-52ee-92a2-c25e7cb387a9',
    name: 'default-site-plugin',
    version: '1c853180fe07a9a95aa030a850c4ab6a',
    pluginOptions: { plugins: [] },
    nodeAPIs: [ 'onCreateNode', 'createPages' ],
    browserAPIs: [],
    ssrAPIs: [],
    pluginFilepath: '/home/adam/Dev/MyBlog'
  },
  payload: {
    id: '1c6cb559-a9f8-5a4f-92ef-ff88ab9df2ab',
    uid: null,
    type: 'newsitem',
    href: 'https://href...',
    tags: [],
    first_publication_date: '2020-08-31T12:30:12+0000',
    last_publication_date: '2020-08-31T13:52:59+0000',
    slugs: [
      'test-entry',
      'testentry'
    ],
    linked_documents: [],
    lang: 'hu',
    alternate_languages: [],
    data: {
      title: [Object],
      date: [Object],
      summary: [Object],
      image: [Object]
    },
    prismicId: 'X0ztURIAANYJZCHY',
    dataString: '...',
    dataRaw: {
      image: [Object],
      title: [Array],
      date: [Array],
      summary: [Array]
    },
    url: undefined,
    internal: {
      type: 'PrismicNewsitem',
      contentDigest: 'be2e3de9942f7868be057212ba2f7c9b',
      counter: 116,
      owner: 'gatsby-source-prismic',
      fieldOwners: [Object]
    },
    _previewable: 'X0ztURIAANYJZCHY',
    children: [],
    parent: null,
    fields: { slug: 'test-entry' }
  },
  addedField: 'slug'
}
```

This indicates for me that the node field creation was successful, but when I query the Gatsby API with graphql I get the following error:

**query**
```
query MyQuery {
  allPrismicNewsitem {
    nodes {
      fields {
        slug
      }
      internal {
        type
      }
    }
  }
}
```

**error**

```
{
  "errors": [
    {
      "message": "Cannot query field \"fields\" on type \"PrismicNewsitem\".",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "stack": [
       ...
      ]
    }
  ]
}
```

The strange thing is in the output there's a slugs field, but it is not present on Gatsby's API.

Any suggestions?

**Comment by MacMorgan** [comment]
Confirmed the same issue, this seems to be limited to types created via this source plugin

**Comment by angeloashmore** [comment]
This happens because the plugin tells Gatsby exactly how each node (i.e. each document from Prismic) should look like. Any additional fields added via `createNodeField` won't be included since it happens outside of the plugin.

You should be able to leverage Gatsby's `createSchemaCustomization` API to tell it about your custom fields, however. Fields made with `createNodeField` are added to the `fields` field. As long as you define what type `fields.slug` is (a `String`, for example), then it should be queriable.

As an aside, I'd recommend using a Link Resolver rather than a custom field to generate a URL/slug. By using the link resolver, each document's `url` field will automatically have the correct URL populated. This means if you reference it anywhere in another document, it will already have the correct URL present.

**Comment by AdamBelakovics** [comment]
Thanks for the answers! Link resolving seems to be the best approach here.

**Comment by jodiedoubleday** [comment]
loosely related to - https://github.com/angeloashmore/gatsby-source-prismic/issues/330

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!
