### ISSUE TITLE
Implementing GraphQuery for build time grand children relationships

### ISSUE THREAD

**Issue by agoldenduck** [prismicio/prismic-gatsby#267]
Hi @angeloashmore,

Thanks so much for this fantastic Prismic Gatsby Source. I am another refugee from the the gatsby-source-prismic-graphql library's issues.

I saw in [this comment](https://github.com/angeloashmore/gatsby-source-prismic/issues/47#issuecomment-493319173) that you are planning to implement GraphQuery. Is there any active plans to support it? 

This would greatly assist our efforts to create pages that are grand children of each other at build time rather than having to dynamically generate the links on the browser.

Thanks

**Comment by angeloashmore** [comment]
Hey @agoldenduck, sorry I didn't reply to this issue!

I'm cleaning out old issues and closing this due to its age. GraphQuery is now possible using the `graphQuery` plugin option as mentioned in your PR.
