### ISSUE TITLE
Plugin does not work for sites hosted from a subdirectory

### ISSUE THREAD

**Issue by anicholls** [prismicio/prismic-gatsby#275]
I have a Gatsby site set up to publish to GitHub pages. This uses the standard GitHub pages URL structure (`https://github.com/pages/user/repo`). I have accounted for this in Gatsby by using the [`pathPrefix` field](https://www.gatsbyjs.com/docs/path-prefix/) in my gatsby-config.js file.

I have Prismic previews configured and working correctly for both my Gatsby dev server, and for a locally served, compiled version of the site. However, previews are not working when viewed in GitHub pages. I get the error `TypeError: typePaths.find is not a function` [here](https://github.com/angeloashmore/gatsby-source-prismic/blob/690a823f67eeade3a52e6176ca033e0cca27684b/src/documentsToNodes.ts#L32), because of a 404 when `gatsby-source-prismic` tries to access the `https://github.com/prismic-typepaths---*.json` route (notice the lack of path prefix/subdirectory here).

After tracking down this URL, it looks like it is hardcoded to reference the domain root:
https://github.com/angeloashmore/gatsby-source-prismic/blob/4e16769220e3e38a0ea8393b5fdb22e84d5190d3/src/usePrismicPreview.ts#L164

I tried including the path prefix in the `typePathsFilenamePrefix` option in the plugin configuration, however that causes  `gatsby build` to fail because this plugin's `gatsby-node.js` tries to source that file from `/public` [here](https://github.com/angeloashmore/gatsby-source-prismic/blob/7893d7204960b8246fe359b9db6ee384f39ee84e/src/gatsby-node.ts#L95). This results in the following error:

`Error: ENOENT: no such file or directory, open '/path/to/repo/public/pages/user/repo/prismic-typepaths---*.json` (note the `pages/user/repo` path prefix)

---

I couldn't find any documentation for hosting a Gatsby + Prismic site with previews on a domain subdirectory, but IMO, this is a bug and should be updated to properly support previews in this context. I'm uncertain if the correct approach is to just reference the `pathPrefix` config variable here, or if there's a better alternative. Provided this is indeed a bug, I would be willing to submit a PR with a bit of guidance. Otherwise, any help/recommendations to fix this error would be much appreciated! Thanks in advance

**Comment by anicholls** [comment]
I seem to have found another related issue. I hardcoded in my subdirectory for [`typePathsRes`](https://github.com/angeloashmore/gatsby-source-prismic/blob/4e16769220e3e38a0ea8393b5fdb22e84d5190d3/src/usePrismicPreview.ts#L164) in my built site so see if I could get things working. This reveals another issue:

1. `withPreviewResolver()` pulls the path for the preview document from `usePrismicPreview()`. 
2. `usePrismicPreview()` generates the path using `resolvedPathResolver = hydratedOptions.pathResolver ?? hydratedOptions.linkResolver`. 
3. The path here should not include the subdirectory path prefix because `withPreviewResolver()` subsequently calls the Gatsby function `navigate(path)` (which expects no prefix) after dispatching the `AddPage` action. 
4. This navigation then causes `withUnpublishedPreview()` to be called. This tries to compare the path of the document generated earlier with `props.location.pathname`. Unfortunately `props.location.pathname` includes the full path, so `"/document" !== "/pages/user/repo/document"`. 
5. I'm now left with a 404 even though I'm on the correct URL.

Since Gatsby's `navigate` function accounts for the path prefix, I cannot add the path prefix in the `pathResolver` or `linkResolver` functions or it will navigate me to `https://github.com/pages/user/repo/pages/user/repo/document` (note the duplicated path prefix). 

I think the fix here is to check `props.path` instead of `props.location.pathname` here: 
https://github.com/angeloashmore/gatsby-source-prismic/blob/master/src/withUnpublishedPreview.tsx#L18.

**Comment by angeloashmore** [comment]
Hi @anicholls,

Thanks for the deep dive into the issue. This makes sense, I didn't account for a site's path prefix.

A PR would be greatly appreciated. Provided `pathPrefix` works at runtime, we should be able to wrap URLs where necessary. Most notably, the `typePaths` URL fetched in `usePrismicPreview` needs `pathPrefix`.

Re: `props.path` vs `props.location.pathname`, I remember running into an issue where `props.path` was either incorrect or empty (can't recall, this was a while ago). On a site with a path prefix, `props.location.pathname` of course does not make sense as it would include the prefix. Ideally, all URLs saved in the context reducer are scoped to the subdirectory (i.e. we store `/my-page`, not `/my-prefix/my-page`).

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. This should be fixed in the latest version of the plugin. If this is still a problem, please open a new issue and I will take a look!
