### ISSUE TITLE
PrismicImageFixedType not compatible with GatsbyPrismicImageFixed

### ISSUE THREAD

**Issue by rubas** [prismicio/prismic-gatsby#295]
The graphql type `PrismicImageFixedType` defined [here](https://github.com/angeloashmore/gatsby-source-prismic/blob/86f391ecbcc699b8872b954306608ef3bc2fdd06/src/gqlTypes.ts#L58) has a not-nullable field `sizes`.

But this field is not a part of the [GatsbyPrismicImageFixed Fragments](https://github.com/angeloashmore/gatsby-source-prismic/blob/86f391ecbcc699b8872b954306608ef3bc2fdd06/fragments.js#L24).

The types are not compatible.

```
export type PrismicImageFixedType = {
  __typename?: "PrismicImageFixedType"
  base64: Scalars["String"]
  src: Scalars["String"]
  srcSet: Scalars["String"]
  srcWebp: Scalars["String"]
  srcSetWebp: Scalars["String"]
  sizes: Scalars["String"]
  width: Scalars["Int"]
  height: Scalars["Int"]
}
```

```
export const GatsbyPrismicImageFixed = graphql`
  fragment GatsbyPrismicImageFixed on PrismicImageFixedType {
    base64
    width
    height
    src
    srcSet
  }
```

`sizes`, `srcWebp` and `srcSetWebp` should be optional in `PrismicImageFixedType`.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!
