### ISSUE TITLE
Query falling on prismic 

### ISSUE THREAD

**Issue by IlyaGit01** [prismicio/prismic-gatsby#315]
Hello ))

Some day ago a update from gatsby-source-prismic-graphql on gatsby-source-prismic v3.3.3
With new plugin I can't reqest field if that field is empty in all documents, but field initialized in custom type. I get error that field is unknown argument.

**Comment by Hahlh** [comment]
Hey @IlyaGit01 )

Could you please copy / screenshot the exact error message?
Did you add your schemas to the gatsby-config and to the schema folder?

'Unknown argument' sounds like an awkward error to get in this context as it should normally return undefined or something along those lines and it shouldn't be an argument at all.

Could you please also copy your query?

**Comment by IlyaGit01** [comment]
This is scheme 
![image](https://user-images.githubusercontent.com/52976805/107184327-6952c900-69f1-11eb-83f6-e921f63dde23.png)
Query
![image](https://user-images.githubusercontent.com/52976805/107184370-7bcd0280-69f1-11eb-803c-6ccae0608139.png)
Error
![image](https://user-images.githubusercontent.com/52976805/107184783-4543b780-69f2-11eb-9444-cb39e5b0e058.png)

**Comment by Hahlh** [comment]
What does the GraphQL-playground tell you about the query? (localhost:8000/__graphql)

Could you please also console.log the complete data object and post it?

**Comment by IlyaGit01** [comment]
![image](https://user-images.githubusercontent.com/52976805/107207414-55b75a80-6a11-11eb-93aa-d73081467059.png )
 GraphQL-playground tell me "Cannot query field name"

**Comment by Hahlh** [comment]
Your config suggests that the name of the custom types is example_type. This means that allPrismicTesto should be invalid for this type. Try prismicExampleType / allPrismicExampleType instead.

I would suggest, that you rebuild your whole query in the GraphQL playground. If you press ctrl + space, you will get suggestions for available queries and fields. Alternatively you could check the integrated docs on the right side.

**Comment by IlyaGit01** [comment]
So it's some strange, because all prismic custom types is valid and I can get fields which not initialized in scheme. I have only one scheme in project now. 
My custom types 
![image](https://user-images.githubusercontent.com/52976805/107211353-7c2bc480-6a16-11eb-83a7-7eea652b50f9.png)
Types in GraphQL-playground
![image](https://user-images.githubusercontent.com/52976805/107211789-13911780-6a17-11eb-9ea3-3d19e1083331.png)

**Comment by Hahlh** [comment]
I would suggest, that you remove all of them but one and make sure that the things I have described above are consistent.
After that, you should be able to move forward with debugging much more confident, if still necessary.

GraphQL can behave strange, if you are not careful with keeping your schemas in Gatsby, in Prismic and in the Gatsby config in sync.

**Comment by IlyaGit01** [comment]
Today I have tested app like you suggested and get strange QraphQl behavior. Situation one, in gatsby-config.js using only one scheme of custom types, but in playground I see all types and not all types have all fields. Situation two, my scheme have some fields like in prismic JSON editor, I rename fields like in documentation. For example, page-title on pageTitle or page_title, it not matter, because fields return null value. But when I request dataRaw instead data, all fields return valid values.  

gatsby-config.js
![image](https://user-images.githubusercontent.com/52976805/107339909-41856300-6ace-11eb-8712-070e68975be3.png)

Scheme
![image](https://user-images.githubusercontent.com/52976805/107340218-9032fd00-6ace-11eb-99ad-cec1c579afba.png)

Graphql playground
![image](https://user-images.githubusercontent.com/52976805/107340395-c6707c80-6ace-11eb-8c2e-980cabc0cd69.png)

My query with empty fields in data and all fields in dataRaw.
![image](https://user-images.githubusercontent.com/52976805/107342606-76df8000-6ad1-11eb-86c2-7697640a4985.png)

Very often qraphql behavior change, it really hard to debugging.

**Comment by Hahlh** [comment]
The path you are using in the config does suggest, that you custom_types folder is outside of src?

**Comment by IlyaGit01** [comment]
And how can I get fields with a hyphen in their name? Such fields cannot be specified in the schema, because there will be an error. If such fields are written via camelCase or snake_case in the schema, they will return with a null value, and not what it actually is. But these fields are in dataRow

**Comment by Hahlh** [comment]
Did moving the folder into src work?

Hyphens should normally not be a problem.
What error is there? Can you please provide screenshots again?

**Comment by IlyaGit01** [comment]
moving the folder into src not working
In prismic my field is meta-description, but in scheme I get error 
![image](https://user-images.githubusercontent.com/52976805/107356859-65eb3a80-6ae2-11eb-8bd0-250cf27980b5.png)
because of it I tred to rename field to metaDescription and meta_description, but it not working. 

![image](https://user-images.githubusercontent.com/52976805/107358052-f5451d80-6ae3-11eb-94b3-8c4394c4739d.png)
In this screenshot, you can see that all the fields in data are empty, and in DataRow, the names of these fields are written with a hyphen and the data returned correctly.

**Comment by Hahlh** [comment]
We need to go step by step here and ignore some of those issues for the moment.
Please follow the following steps so that we can ensure the basic function, receiving data for a simple request, in a controlled environment  

1. Delete all types, that you have created for testing
2. Create a new repeatable type called "**test_type**". Please make also sure that the API ID is "**test_type**"
2. Make sure that test_type contains only a single title field called "**test_title**" in Prismic and nothing else:

![image](https://user-images.githubusercontent.com/45669613/107374825-5242d280-6ae8-11eb-9074-6d6558a188d6.png)

3. Make sure that there is a folder called "**schemas**" in your src folder
4. Make sure that in this folder there is a file with the name "**test_type.json**"
5. in this file you should have this code:
```
{
  "Main": {
    "test_title": {
      "type": "StructuredText",
      "config": {
        "single": "heading1, heading2, heading3, heading4, heading5, heading6",
        "label": "test_title"
      }
    }
  }
}
```
5. Make sure that in gatsby-config.js only this one type is added and that the path is declared as follows:
```
schemas: {
    test_type: require("./src/schemas/test_type.json")
 }
```
6. Go to your documents and create an instance of test_type. Save and publish it.
![image](https://user-images.githubusercontent.com/45669613/107377042-d433fb00-6aea-11eb-8527-59b8514f7842.png)
7. Start up your gatsby server with "npm run start"
8. Go to localhost:8000/__graphql
9. Enter this query
```
{
  allPrismicTestType {
    edges {
      node {
        data {
          test_title {
            text
          }
        }
      }
    }
  }
}
```
10. Check for the response:
![image](https://user-images.githubusercontent.com/45669613/107377453-486e9e80-6aeb-11eb-8fa5-206fbf2ebdda.png)

Please also remember, that if you change something about the json file or anything related to pulling content from Prismic in, you will likely have to restart your Gatsby server.

If this works, then all other oddities, that still exist, can be cleared up.

**Comment by MarcMcIntosh** [comment]
Running `gatsby clean` can sometimes help :)

**Comment by angeloashmore** [comment]
Thanks @Hahlh and @MarcMcIntosh for helping here!

Yes, my first suggestion is to clear your Gatsby cache. Sometimes Gatsby's cache of the types gets out of sync with what you provided in your JSON files.

Run `gatsby clean` in your project to clear the `.cache` and `public` folder. They will be rebuilt the next time you run `gatsby develop` or `gatsby build`. This isn't something that is required every time.

If that doesn't work, are you able to share your repository on GitHub? If not, are you able to create a sample repository with the same problem? Everything @Hahlh is recommending is correct, but it may be easier for us to check your code if we can view it directly.

---

Re: hyphenated field names, this is unfortunately a limitation of GraphQL, not Prismic or the plugin, so it isn't something that can be supported. What we can do, however, is automatically replace hyphens with something else, such as `__`. So a field like `my-field` could be renamed to `my__field`.

This can be included in the next major version of the plugin being worked on now if you think that would help.

**Comment by IlyaGit01** [comment]
This would be great because in the working version of the site on prismic, the fields use a hyphen, which does not support the new plugin. This would allow you to keep the old field names and not change the code in the working version of the site, but only deal with the new version of the site.

**Comment by angeloashmore** [comment]
@IlyaGit01 When you query for fields with hyphens using the GraphQL plugin, what does your query look like? It's probably a good idea for us to match how the official GraphQL API handles the hyphens.

**Comment by MarcMcIntosh** [comment]
The prismic graphql-api transforms kebab-case (hyphens)  to camelCase, that's how we approached the issue here :)

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. The current version of the plugin will automatically transform field names with `-` into `_`. If this is still a problem, please open a new issue and I will take a look!
