### ISSUE TITLE
Problems using with Apollo Client

### ISSUE THREAD

**Issue by alexcmartens** [prismicio/prismic-gatsby#318]
Thanks @Hahlh, that means a lot! Always open to feedback if you think there's anything that can be done better as well.

---

@alexcmartens The REST API allows us to pull all data from repositories quickly and efficiently. The resulting data is the same as using the GraphQL API, but with a slightly different shape in some areas. The issue @Hahlh linked above details some of the reasons using the GraphQL API would not be possible, at least at this time.

I would recommend using only static data in your Gatsby site as much as possible. This will result in a quicker and more state-less end result. If, for some reason, you do need to query the Prismic repository at run time, there certainly is nothing stopping you from using Prismic's GraphQL or REST API directly.

If you have some time, I'd also like to hear your use case where mixing static and dynamic queries is helpful to see if there's any way the plugin could make that process easier.

_Originally posted by @angeloashmore in https://github.com/angeloashmore/gatsby-source-prismic/issues/307#issuecomment-776148249_

**Comment by alexcmartens** [comment]
Thanks for your interest!

So I have a table of data that requires pagination, like a “Show More” button, but it also has a number of filters and sorting options that can be applied to it. Generating all of the possible combinations of filters and paginated results staticly seems incredibly cumbersome.

gatsby-source-prismic-graphql allowed you to dynamically fetch data by applying new values to your page query. I have been trying to accomplish something like this by combining gatsby-source-prismic with the Apollo client, where the initial set of data could be static, but if a filter changes it would dynamically load a new set of data, or append additional data if the ‘Show More’ button is clicked.

gatsby-source-prismic-graphql allowed you to dynamically fetch data by applying values to the variables defined in your page query as follows:

```
import React from 'react';
import { graphql } from 'gatsby';

export const query = graphql`
  query Example($cursor: String, $tags: [String!]) {
    prismic {
      allEvents(after: $cursor, tags: $tags) {
        edges {
          node {
            title
          }
        }
      }
    }
  }
`;

export default function Example({ data, prismic }) {
  const handleClick = () =>
    prismic.load({
      variables: { cursor: cursor, tags: tags },
      query, // (optional)
      fragments: [], // (optional)
    })
    .then(res => /* Do something with the data */);

  return (
    // ... data
    <button onClick={handleClick}>Show More</button>
  );
}
```

Unfortunately, with gatsby-source-prismic, there doesn't appear to be a cursor in the page query that I can provide to the Apollo client if the user clicks the 'Show More' button. Additionally, I can't use the Gatsby GraphiQL tool to generate the Apollo client query since it leverages Prismic's GraphQL API instead of the REST API.

I loved the way that gatsby-source-prismic-graphql seamlessly allowed you to work with static and dynamic data. But, if I am not thinking through this correctly, please let me know. Thanks!

**Comment by angeloashmore** [comment]
@alexcmartens Thanks, that all makes sense. I'll have to come back to this later, but just wanted to let you know I've read through your message.

In the mean time, it is possible to have pagination with "Load More" functionality while keeping everything static. One such method is this: [`gatsby-plugin-paginated-collection`](https://github.com/WalltoWall/gatsby-plugin-paginated-collection)

Once filters are introduced, however, it does become more complicated and I would suggest moving to a client-side, dynamic query like you're currently doing.

Knowing that the GraphQL schema in Gatsby is different from Prismic's GraphQL API, what kind of data would be helpful in bridging the gap between the two? Specifically for the type of functionality you need.

**Comment by alexcmartens** [comment]
Yeah, our preferred way of doing pagination is with "Load More" functionality. That plugin maybe helpful in the future when filters aren't required. Thanks!

There are probably different ways to do pagination, but I have always used the GraphQL cursor. I was looking for it in the GraphiQL inspector and realized that it is probably missing because the plugin uses the REST API. If you have a different way to accomplish this task let me know.

**Comment by MarcMcIntosh** [comment]
Hi @alexcmartens 

I don't know how much thhis will help, but there is an alternative to using the Apollo plugin, that would be https://github.com/gatsbyjs/gatsby-graphql-toolkit

I guess another way would be to use prismic-javascript client side to fetch the data? but this would prevent you from using graphql :/

**Comment by alexcmartens** [comment]
I might have to move away from GraphQL because you can’t preform a query based off of a group of "custom tags" from Prismic. To further clarify, I have the need to define a set of tags and categorize data based on them. Unfortunately, with GraphQL, when you have a repeatable group of them, you cannot query data in reference to them. Apparently, this isn’t a problem with their REST APIs. This is really frustrating!

https://community.prismic.io/t/how-do-you-query-by-a-content-relationship-in-a-group-but-in-graphql/1963

**Comment by angeloashmore** [comment]
@alexcmartens I hear you - from my understanding, the GraphQL API is missing features that are provided by the REST API. I'm not sure what is on the roadmap for Prismic's GraphQL API, but I wouldn't shy away from using the REST API if it can handle what you need.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still a problem, please open a new issue and I will take a look!
