### ISSUE TITLE
Schemas validation

### ISSUE THREAD

**Issue by My3bIKAHT** [prismicio/prismic-gatsby#320]
Spent significant amount of time trying to find out why linkResolver not being applied to some content types during build process. Realised that I placed schema file into folder, but never added reference into plugin config. 

I wish there was some way to validate schemas, both amount and how up-to-date they are. Or even pull and sync schemas from repo before the rest of the data.

**Comment by angeloashmore** [comment]
Hi @My3bIKAHT, this is definitely a common problem and something that will be addressed in the next major version of the plugin (V4). It is currently in active development with plans to have a public beta hopefully within the next month.

You can see the V4 roadmap here: https://github.com/angeloashmore/gatsby-source-prismic/issues/307
And a more detailed writeup of the changes: https://labs.walltowall.com/gatsby-source-prismic-v4-roadmap/

In addition to the plugin checking if you provided all schemas, Prismic is working on providing an API for schemas to be pulled automatically without you needing to explicitly provide them.

You can see the WIP PR with some explanations from Prismic here: https://github.com/angeloashmore/gatsby-source-prismic/pull/316

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. Plugin option validation is more advanced now and will tell you if a schema is missing. If this is still a problem, please open a new issue and I will take a look!
