### ISSUE TITLE
Preview is showing published content only

### ISSUE THREAD

**Issue by cjost1988** [prismicio/prismic-gatsby#327]
Hello,

sadly I am not able to get the preview running. I've already reduced my application to the basic-st version possible but no success.

**What I've done**
1. Added the component `gatsby-source-prismic`, including `pages/preview.js` with `linkResolver` and `wrapRootElement` API
2. Added a page template `src/templates/Homepage.js` containing a Query to get a document by `id`
3. Add a createPages API in `gatsby-node.js` that is getting `homepages` and executing the `createPage` with document context for `src/templates/Homepage.js`
4. So far everything works, page loads and data is correct
5. I go to the prismic backend and hit the preview button on the homepage with unpublished content
6. I am redirected to my `localhost:8000/preview...` and it loads some stuff in the background via XHR
7. Once, so I've the feeling, data loading is done it redirects to the proper page
8. But shows only the published content and not the unpublished

I am kinda lost :D And I am feeling like a looser after spending loads of hours trying to find out whats wrong.

**gatsby info:**
```
  System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.82
    Firefox: 86.0
    Safari: 14.0.1
  npmPackages:
    gatsby: ^3.0.0 => 3.0.4
    gatsby-image: ^3.0.0 => 3.0.0
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-sharp: ^2.11.2 => 2.14.3
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-source-prismic: ^3.3.4 => 3.3.4
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
  npmGlobalPackages:
    gatsby-cli: 2.8.9
```

FYI: I've also added the _previewable field to graphql query since I read that this could be an issue because this field is used to identify differences between the original document and the preview version of the document.

Also not working :S

In addition:
I can see that the /search queries return the proper document that contains the unpublished changes and no other document is returned either. So I think there is an issue somewhere replacing the nodes.

To better understand I created a sample repository containing my setup and a not working preview environment :D
https://github.com/cjost1988/gatsby-prismic-preview

Maybe this helps to identify the issue. Sadly I can also not setup gatsby-source-prismic as a local build package. Building the package works with yarn build but when I add the package as yarn link to the project and start the server it's giving me an error related to PrismicImageType.

Thanks for your help in advance.

Cheers, 
Chris

**Comment by cjost1988** [comment]
FYI: I've also added the `_previewable` field to graphql query since I read that this could be an issue because this field is used to identify differences between the original document and the preview version of the document.

Also not working :S

**Comment by cjost1988** [comment]
To better understand I created a sample repository containing my setup and a not working preview environment :D 
https://github.com/cjost1988/gatsby-prismic-preview

Maybe this helps to identify the issue. Sadly I can also not setup `gatsby-source-prismic` as a local build package. Building the package works with `yarn build` but when I add the package as `yarn link` to the project and start the server it's giving me an error related to `PrismicImageType`.

**Comment by madeleineostoja** [comment]
Not the maintainer of this package, but have you looked into the withUnpublishedPreview HOC? https://github.com/angeloashmore/gatsby-source-prismic/blob/master/docs/previews.md#withUnpublishedPreview

**Comment by cjost1988** [comment]
Thank you @madeleineostoja for your response.
Yes, I've looked into the `withUnpublishedPreview` but as I read that
> Because the document is unpublished, the page does not yet exist in the built version of the Gatsby site.
I thought this is only needed if I want to preview pages that are not published at all yet.

Is this also needed if I want to see unpublished changes to documents that have been published at least once?

**Comment by cjost1988** [comment]
I got a working preview with this repository https://github.com/prismicio/gatsby-blog but I don't know what I exactly did wrong. I will now compare it, maybe I find it out :)

**Comment by jodiedoubleday** [comment]
I've not looked extensively at your example repo bit I remember when I started out with this repo I had the same issue.

I tracked it down the the 404 you need to specify the template map (all the types of template you have)

Take a look at your 404 and the one you for working from Prismic - https://github.com/prismicio/gatsby-blog/blob/master/src/pages/404.js

**Comment by cjost1988** [comment]
@jodiedoubleday thank you already for your response and that you took time having a look.

@jodiedoubleday yea, I got the preview working for all documents that were published at least once. But for the documents that were never published so far the preview does not work and only shows the 404 page.

> Take a look at your 404 and the one you for working from Prismic - https://github.com/prismicio/gatsby-blog/blob/master/src/pages/404.js

I compared it and my types are mapped to the corresponding template files.
It is defined exactly the same way :S 

```javascript
import React from 'react'
import { withUnpublishedPreview } from 'gatsby-source-prismic'
import Homepage from '../templates/Homepage'
import ServiceOverview from '../templates/ServiceOverview'

export default withUnpublishedPreview(Page404, {
  templateMap: {
    homepage: Homepage,
    prismicHomepage: Homepage,
    service_overview: ServiceOverview,
    prismicServiceOverview: ServiceOverview,
    // ...
  },
})
```

One thing that came to my mind was that I generate the pages by `gatsby-node.js` which is passing `id` and `lang` to each template file which will be used in the template query to find the corresponding document in the proper locale.

But I am kinda lost here :D 
In the PHP world I would start debugging but in the JS world I am not that familiar with this.

**Comment by angeloashmore** [comment]
This issue is stale and may be fixed in a recent version. Please update to the latest version and try again. If the issue continues to be a problem, please open a new issue. Thank you!

See the documentation for guides on updating to the latest versions: [Gatsby + Prismic Migration Guides](https://github.com/prismicio/prismic-gatsby/tree/main/docs#migration-guides)
