### ISSUE TITLE
Integrate analytics to better understand usage

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-gatsby#363]
Understanding how users use the plugins will help drive future development and documentation efforts. We want to make sure the right thing is being given attention, and having analytics will help direct it.

Ideally this is ~opt-out~ opt-in (thanks @ohlr), with a clear message to users. This is open to discussion.

**Comment by ohlr** [comment]
Analytics should be opt-in as per most privacy laws.

**Comment by angeloashmore** [comment]
Yes, you're right. Good point!
