### ISSUE TITLE
Timed out when fetching nodes

### ISSUE THREAD

**Issue by jacknbeans** [prismicio/prismic-gatsby#366]
I tried searching for my issue already, but couldn't find anyone having the same problem as I am currently.

I don't have this happening all the time, but every so often the plugin will fail to fetch anything from the REST API. The error returned is this (removed all sensitive information and replaced with `REDACTED`:
```
ERROR #11321  PLUGIN

"gatsby-source-prismic" threw an error while running the sourceNodes lifecycle:

request to https://REDACTED.cdn.prismic.io/api/v2/documents/search?page=1&pageSize=100&access_token=REDACTED&fetchLinks=&lang=*&ref=YJuQzxEAACAAO38D&q=%5B%5D failed, reason: connect ETIMEDOUT
65.9.84.91:443



  FetchError: request to https://REDACTED.cdn.prismic.io/api/v2/documents/search?page=1&pageSize=100&access_token=REDACTED&fetchLinks=&lang=*&ref=YJuQzxEAACAAO38D&q=%5B%5D failed, reason: connect ETIME
  DOUT 65.9.84.91:443
  
  - index.js:1393 ClientRequest.<anonymous>
    [node-fetch-npm-2.1.2-696de0a8dd-9f9fcdc37d.zip]/[node-fetch]/lib/index.js:1393:11
  
  - node:events:365 ClientRequest.emit
    node:events:365:28
  
  - node:_http_client:447 TLSSocket.socketErrorListener
    node:_http_client:447:9
  
  - node:events:365 TLSSocket.emit
    node:events:365:28
  
  - destroy:193 emitErrorNT
    node:internal/streams/destroy:193:8
  
  - destroy:158 emitErrorCloseNT
    node:internal/streams/destroy:158:3
  
  - task_queues:83 processTicksAndRejections
    node:internal/process/task_queues:83:21
```

This occurs when running `gatsby develop` (haven't tried running a production build yet, but I assume the same thing would occur there). If I copy the URL that it's trying to fetch from and paste it into a browser, I'm able to get the requested data from the API, so not sure why it's timing out in Gatsby. 

It seems that if I do some sort of update on the backend (e.g. add an access token, update access token, etc.) then the problem goes away for a while. I'm not 100% certain that that is what's fixing it, but it's something that I've done and I noticed that the fetch request would succeed after doing those actions.

Any ideas what this could be?

EDIT: Forgot to add which version of the plugin I'm using, which is `3.3.6`

EDIT2: Doesn't appear that what I was doing in the Prismic backend is having any effect on this. Since I was updating the backend as I mentioned and it would still break. The only thing that seems to work is retrying the `gatsby develop` command. I should also mention that I'm using Gatsby v3 and Yarn v2, not sure if that has any effect on this.

**Comment by angeloashmore** [comment]
Hi @jacknbeans, sorry you didn't get a reply about this sooner. It's difficult to tell exactly what was causing that problem since the network request simply failed.

You could try configuring the plugin to fetch your repository content in smaller batches. By default, the plugin will fetch content 100 documents at a time. This may result in a long API response delay. You can configure this number using the `pageSize` option ([see the API reference here](https://prismic.io/docs/technical-reference/gatsby-source-prismic#configure-the-plugin)).

```js
// gatsby-config.js
{
  resolve: "gatsby-source-prismic",
  options: {
    repositoryName: "your-repo-name",
    pageSize: 50
  }
}
```

I'm going to close this issue since it is quite old, but please feel free to reply back here if this is still an issue and I will reopen it.
