### ISSUE TITLE
Make GraphQL fields non-nullable where possible

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-gatsby#381]
Most fields are left nullable for the best compatibility with data coming from the Prismic API. There are some fields, however, that we know will always contain a value.

For example, a StructuredText field will always have `html` and `text` values as `String!`, even if they compute to empty strings.

See comments from @cometkim here: https://github.com/angeloashmore/gatsby-source-prismic/issues/377#issuecomment-850224850

**Comment by cometkim** [comment]
- boolean
- list and list item
- data field of custom type
- body field of custom type
- primary field of slices
- `localFile` field of image (since v4)

and

```
    type PrismicLinkType {
      isBroken: Boolean!
      url: String!
      target: String!
      raw: JSON!
    }

    type PrismicImageDimensionsType {
      width: Int!
      height: Int!
    }

    type PrismicStructuredTextType {
      html: String!
      text: String!
      raw: JSON!
    }

    type PrismicGeoPointType {
      latitude: Float!
      longitude: Float!
    }
```

**Comment by cometkim** [comment]
There will be conflict issue when making primary fields as non-nullable. 
```
Fields "primary" conflict because they return conflicting types "PrismicTeamContentsDataMainBodyKeyVisualPrimary!" and "PrismicTeamContentsDataMainBodyTitleAndIllustrationPrimary".
 Use different aliases on the fields to fetch both if this was intentional.

GraphQL request:3:5
2 |   fragment PrismicTeamContentsDataMainBodyKeyVisual_data on PrismicTeamContentsDataMainBodyKeyVisual {
3 |     primary {
  |     ^
4 |       key_visual_image {

GraphQL request:3:5
2 |   fragment PrismicTeamContentsDataMainBodyTitleAndIllustration_data on PrismicTeamContentsDataMainBodyTitleAndIllustration {
3 |     primary {
  |     ^
4 |       key_text

```

We can narrow down it to additional nested type to avoid duck typing issue.

**Comment by angeloashmore** [comment]
This issue is stale and may be fixed in a recent version. Please update to the latest version and try again. If the issue continues to be a problem, please open a new issue. Thank you!

See the documentation for guides on updating to the latest versions: [Gatsby + Prismic Migration Guides](https://github.com/prismicio/prismic-gatsby/tree/main/docs#migration-guides)
