### ISSUE TITLE
[Critical] The preview data API seems broken for Rich Text fields

### ISSUE THREAD

**Issue by benjaminwaterlot** [prismicio/prismic-gatsby#401]
Hello @angeloashmore,

First, thanks for your answers on my other issues :)

---

**Starting yesterday, the preview API started to return an inconsistent (broken) data schema for Rich Text fields.**
The endpoint called and which returns this broken data schema is:

```
https://shine.cdn.prismic.io/api/v2/documents/search?ref={"shine.prismic.io":{"preview":"https://shine.prismic.io/previews/YNtMihIAACwAY9_3:YNwcpRIAACsAZ3pG?websitePreviewId=YMMqohIAACMAZqn6"}}&access_token=REDACTED_FOR_ISSUE&lang=*&page=1&pageSize=100
```

My components expect data of type:

```
{
  "my_rich_text_field": {
    "raw": [
      {
        "type": "heading2",
        "text": "A rich text heading 2",
        "spans": []
      }
    ]
  },
}
```

But, since yesterday, for no visible reason, and only when preview kicks in, it receives data of type:

```
{
  "my_rich_text_field": [
      {
        "type": "heading2",
        "text": "A rich text heading 2",
        "spans": []
      }
    ]
}
```

<details>
  <summary>Full response schema:</summary>
  
```
    {
      "id": "YMoDzRMAACQAjMfm",
      "uid": "entreprises",
      "url": null,
      "type": "page",
      "href": "https://shine.cdn.prismic.io/api/v2/documents/search?ref=https%3A%2F%2Fshine.prismic.io%2Fpreviews%2FYNtMihIAACwAY9_3%3AYNwcpRIAACsAZ3pG%3FwebsitePreviewId%3DYMMqohIAACMAZqn6&q=%5B%5B%3Ad+%3D+at%28document.id%2C+%22YMoDzRMAACQAjMfm%22%29+%5D%5D",
      "tags": [],
      "first_publication_date": "2021-06-16T13:59:47+0000",
      "last_publication_date": "2021-06-16T15:28:18+0000",
      "slugs": ["le-compte-pro-qui-simplifie-la-gestion-devotre-entreprise"],
      "linked_documents": [],
      "lang": "fr-fr",
      "alternate_languages": [],
      "data": {
        "indexed": true,
        "meta_title": null,
        "meta_description": null,
        "social_media_title": null,
        "social_media_thumbnail": {},
        "body": [
          {
            "slice_type": "header",
            "slice_label": null,
            "items": [{}],
            "primary": {
              {
                "my_rich_text_field": [
                    {
                      "type": "heading2",
                      "text": "A rich text heading 2",
                      "spans": []
                    }
                  ]
              },
...
```

</details>

---

**Note :** **The Prismic API used on `yarn dev`** (or `yarn build`) follows, as expected, the original schema.

So my pages display correctly, then break when the preview kicks in.

Tested on `gatsby-plugin-prismic-previews@^4.0.0-beta.18` and `gatsby-plugin-prismic-previews@^4.0.0-beta.20`.

---

**Workaround**

My workaround is to pass to the render prop of `<RichText />` the following : `render={ my_rich_text_field.raw ??  my_rich_text_field }`, to allow for published data (with the left operand of `??`) and preview data (the right operand).

**Comment by angeloashmore** [comment]
Hey @benjaminwaterlot, it looks like the Rich Text field isn't being converted during the preview properly. Normally this would result in an error being displayed.

When this happens, do you see any error printed to the DevTools console?

**Comment by benjaminwaterlot** [comment]
Hey @angeloashmore :)

This is not related to the front-end and Gatsby stack, so nothing in the console.

It's the external **Prismic preview endpoint** that doesn't return the same data types as before.

In my network tab, the following call:

```
https://shine.cdn.prismic.io/api/v2/documents/search?ref={"shine.prismic.io":{"preview":"https://shine.prismic.io/previews/YNtMihIAACwAY9_3:YNwcpRIAACsAZ3pG?websitePreviewId=YMMqohIAACMAZqn6"}}&access_token=REDACTED_FOR_ISSUE&lang=*&page=1&pageSize=100
```

Returns the following data, which is _not_ correct for Rich Text fields (see my comparison in the original post) and changed suddenly (I think it was on June 29th). 

[preview-result.json.zip](https://github.com/angeloashmore/gatsby-source-prismic/files/6795479/preview-result.json.zip)

Instead of an object with a `raw` array prop (just like `gatsby-source-prismic`), the Rich Text fields of this preview endpoint now contain only an array.

**Comment by angeloashmore** [comment]
Hey @benjaminwaterlot, I apologize for the delayed response. I thought I had responded before.

The data from the Prismic API will not look like the data you receive from Gatsby. The data is processed after receiving it from the API in order to shape it like Gatsby's API from `gatsby-source-prismic`.

When you preview a document, it should automatically transform it into an object that contains `raw`. If it is not transforming, it means the preview system is not correctly determining the type of the field.

There was a fix published recently that made sure an error was displayed when a field type cannot be determined. Can you try with the latest version and let me know if you receive an error when previewing? It should read something like "Not type found for…"

Thanks!

**Comment by kb1995** [comment]
@angeloashmore I'm coming from #430 and I'm experiencing a similar problem like @benjaminwaterlot 

I have a `rich_title` which is an alias to `title`. My graphql query looks like this

```
              rich_title: title {
                raw
              }
```

When not in preview, it's working as expected.

```
<RichText render={data.primary.rich_title.raw} />
```

is outputting the correct title. 

However, when I preview, it looks like that this turns into an `undefined`.

I debugged it in console.log and it looks like while the preview is loading, it outputs the correct json several times but then it changes into `undefined`.

I'm using the latest version of the package (4.1.0)

Any help will be greatly appreciated!

**Comment by angeloashmore** [comment]
Hey @kb1995, alias are not supported in previews. During a preview, you are not using Gatsby's GraphQL API so the `rich_title` => `title` alias is no longer represented anywhere.

If you must use aliases, you have access to a `isPrismicPreview` prop that you can use to determine if you should access `rich_title` or `title`. The prop will be `true` or `false` depending on if a preview session is active.

You can fine more details in the Limitations doc here: https://github.com/prismicio/prismic-gatsby/blob/main/packages/gatsby-plugin-prismic-previews/docs/limitations.md

(This document will need to be migrated to the Prismic website, but you can view it on GitHub for now)

**Comment by angeloashmore** [comment]
I think the original issue was solved here, but please feel free to comment here or open a new issue if this is still a problem. Thanks!
