### ISSUE TITLE
IntegrationType  not working with createSchemaCustomization in v4

### ISSUE THREAD

**Issue by jsauca** [prismicio/prismic-gatsby#429]
### Versions

- gatsby-source-prismic: v4
- node: 15.0.1

### Reproduction

I am creating foreign-key relations with the createTypes action from gatsbyjs. 

Unfortunately what use to work in gatsby-source-prismic: v3 does not work in gatsby v4.

- **Previous code for Gatsby v3 (it works)**
product is a shopify integration field. product.id  & product.admin_graphql_api_id are extracted to link other custom data types (productShopify & productReviews).
```js
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions;
  const typeDefs=`
    type PrismicProductDataType implements Node {
      product: PrismicShopifyProduct
      productShopify: ShopifyProduct @link(by: "shopifyId", from: "product.admin_graphql_api_id")
      productReviews: ProductReviews @link(by: "productId", from: "product.id")
    }
    type PrismicShopifyProduct @dontInfer {
      admin_graphql_api_id: String!
      id: Int!
    }
  `;
  createTypes(typeDefs);
}
```

- **Code for Gatsby v4 (it does not work)**
productShopify and productReviews return null.
It seems that PrismicProductDataProductIntegrationType does not return any data during build time?
Hence the foreign key relations are not created.
```js
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions;
  const typeDefs=`
    type PrismicProductDataType implements Node {
      product: PrismicProductDataProductIntegrationType
      productShopify: ShopifyProduct @link(by: "shopifyId", from: "product.admin_graphql_api_id")
      productReviews: ProductReviews @link(by: "productId", from: "product.id")
    }
    type PrismicProductDataProductIntegrationType @dontInfer {
      admin_graphql_api_id: String!
      id: ID!
    }
  `;
  createTypes(typeDefs);
```

Thanks for your help.

**Comment by angeloashmore** [comment]
Hey @jsauca, I'm testing this out on my side now. To confirm, are you using `gatsby-source-prismic` v4 or v5?

Can you run `gatsby info` and paste the result here?

Thanks!

**Comment by angeloashmore** [comment]
In the meantime, assuming you are using `gatsby-source-shopify` v5, you could try the following:

```
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions

  const typeDefs = `
    type PrismicProductDataType {
      product: ShopifyProduct @link(by: "admin_graphql_api_id")
    }
  `

  createTypes(typeDefs)
}
```

This will replace the `product` data field in your `PrismicProduct` document with a link to the `ShopifyProduct` node. It will match the `admin_graphql_api_id` field in both nodes to create the link.

**Comment by angeloashmore** [comment]
I'm going to close this as schema customizations are working as expected. The IDs returned from `gatsby-source-shopify` and the IDs returned by Prismic's Shopify Integration Fields are different which could be causing this to appear broken.

This may require a special resolver to be passed to `createTypes`.
