### ISSUE TITLE
Add pageSize customization

### ISSUE THREAD

**Issue by matthewlein** [prismicio/prismic-gatsby#435]
I have received an email that prismic will be blocking large api responses soon. I believe some of these are coming from the primsic-gatsby plugin to build all the prismic pages. The easiest solution is lowering pageSize from 100 to something smaller, but I don't think this can be configured in the plugin. 

I would like to be able to set `pageSize` in the config to any number and have it use that to build the pages.

**Comment by angeloashmore** [comment]
Hey @matthewlein, thanks for the suggestion. This sounds like a good idea.

I'm currently refactoring parts of the plugin that currently would conflict with adding a `pageSize` option. I'll leave this issue open for now and will add the option once the refactor is ready to merge. This shouldn't be long - hopefully within the week.

Thanks!

**Comment by matthewlein** [comment]
This is currently blocking all my builds. Can you point me to where I can hack a hardcoded value into the plugin in a fork until this is added? I can't make any sense of this repo and code...

**Comment by angeloashmore** [comment]
@matthewlein Sorry for the delay! I'll add the option and worry about updating it for the refactor later. I'll post here once it's published.

**Comment by angeloashmore** [comment]
@matthewlein Thanks for your patience! The PR has been merged (https://github.com/prismicio/prismic-gatsby/pull/456).

You can update to the latest versions which now has a `pageSize` option.

- `gatsby-source-prismic`: `v4.2.0`
- `gatsby-plugin-prismic-previews`: `v4.2.0`

Then in `gatsby-config.js`:

```js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-source-prismic',
      options: {
        pageSize: 50,
      }
    },

    // If you use gatsby-plugin-prismic-previews:
    {
      resolve: 'gatsby-plugin-prismic-previews',
      options: {
        pageSize: 50,
      }
    },
  ],
}
```

**Comment by matthewlein** [comment]
@angeloashmore Thanks for the quick turnaround!

The update turned out to be pretty lengthy, I was on 3.x, but it all worked in the end. Builds resumed!

**Comment by angeloashmore** [comment]
Great! Glad to hear it's working for you.

Hopefully you found the V3 to V4 migration guide. In case you didn't, here's a reference: https://prismic.io/docs/technologies/gatsby-source-prismic-v3-to-v4
