### ISSUE TITLE
"Cannot use import statement outside a module" when testing components using gatsby-plugin-prismic-previews

### ISSUE THREAD

**Issue by mudge** [prismicio/prismic-gatsby#436]
### Versions

- gatsby-source-prismic: 4.1.2
- gatsby-plugin-prismic-previews: 4.1.2
- node: 14.17.5

### Reproduction

Please see https://github.com/mudge/gatsby-plugin-prismic-previews-test-case for a git repository that demonstrates the failing behaviour.

See the following additional details but this seems to be due to the presence of un-transpiled ES6 code in the `gatsby-plugin-prismic-previews` plugin, specifically line 54 of `node_modules/gatsby-plugin-prismic-previews/dist/index.js` which uses the `import` keyword.

<details open>
<summary>Additional Details</summary>
<br>

The [first significant commit](https://github.com/mudge/gatsby-plugin-prismic-previews-test-case/commit/3184676ada864b044eb7f83448c98943ff195718) has a passing test suite based on the default Gatsby starter template (using `npm init gatsby` and going with the default options) and following the [Prismic tutorial](https://prismic.io/docs/technologies/tutorial-gatsby) for integrating with an existing Prismic repository.

The [second commit](https://github.com/mudge/gatsby-plugin-prismic-previews-test-case/commit/8ca6ff5268f3227e8d96ab60f34df62b6ea791d0) adds `withPrismicPreview` and causes the tests to fail with the following error:

```
 FAIL  src/pages/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/mudge/Downloads/my-gatsby-site/node_modules/gatsby-plugin-prismic-previews/dist/index.js:54
    import {
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import * as React from "react";
    > 2 | import { withPrismicPreview } from "gatsby-plugin-prismic-previews";
        | ^
      3 |
      4 | // styles
      5 | const pageStyles = {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1517:14)
      at Object.<anonymous> (src/pages/index.js:2:1)
```

The following test case is enough to exhibit the behaviour:

```jsx
import React from "react";
import renderer from "react-test-renderer";
import IndexPage from "./index";

describe("IndexPage", () => {
  it("renders correctly", () => {
    const tree = renderer.create(<IndexPage />).toJSON();

    expect(tree).toMatchSnapshot();
  });
});
```

</details>

### Steps to reproduce

* Install `gatsby-source-prismic`, `gatsby-plugin-prismic-previews` and `gatsby-plugin-image` into the default Gatsby starter template (`npm init gatsby`)
* Set up unit testing with Jest as per the [official Gatsby documentation](https://www.gatsbyjs.com/docs/how-to/testing/unit-testing/)
* Set up `src/pages/index.js` to use `withPrismicPreview` as per the [Prismic tutorial](https://prismic.io/docs/technologies/tutorial-6-preview-deploy-gatsby) by wrapping the `IndexPage` component with `withPrismicPreview` and the minimal options
* Attempt to load the default `IndexPage` in a Jest unit test

### What is expected?

The test suite should run and pass.

### What is actually happening?

Jest fails with the following error:

```
 FAIL  src/pages/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/mudge/Downloads/my-gatsby-site/node_modules/gatsby-plugin-prismic-previews/dist/index.js:54
    import {
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import * as React from "react";
    > 2 | import { withPrismicPreview } from "gatsby-plugin-prismic-previews";
        | ^
      3 |
      4 | // styles
      5 | const pageStyles = {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1517:14)
      at Object.<anonymous> (src/pages/index.js:2:1)
```

**Comment by mudge** [comment]
Altering the default Jest configuration in `jest.config.js` to transpile `gatsby-plugin-prismic-previews` as follows causes the test suite to run and pass:

```javascript
  transformIgnorePatterns: [`node_modules/(?!(gatsby|gatsby-plugin-prismic-previews)/)`],
```

However, the tests will then emit the following warnings:

```
(node:39794) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39794) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:39794) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by angeloashmore** [comment]
Hi @mudge,

What you found is correct: the plugin contains code with ES Modules (it is transpiled but not converted to CommonJS). This is done since Gatsby transpiles `node_modules` as part of its bootstrap and build stages.

Your `transformIgnorePatterns` is correct. You can add any non-CommonJS packages to that list.

I believe Jest recently changed their default test environment to `node`. This means browser-specific APIs like `document` and `window` are not available by default. Could you try changing your test environment to `browser` ([more details here](https://jestjs.io/docs/configuration#testenvironment-string))?

You can add this to your `jest.config.js` file:

```js
// jest.config.js

module.exports = {
  // alongside your other options...
  testEnvironment: `jsdom`
};
```

**Comment by mudge** [comment]
Hi @angeloashmore,

Thanks for the prompt response. I added `jsdom` with `npm install --save-dev jsdom` and updated my `jest.config.js` as you suggest and that--along with the aforementioned `transformIgnorePatterns` change--seems to fix the issue:

```
> my-gatsby-site@1.0.0 test /Users/mudge/Downloads/gatsby-plugin-prismic-previews-test-case
> jest

 PASS  src/pages/index.test.js
  IndexPage
    ✓ renders correctly (17 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        2.818 s
Ran all test suites.
```

Perhaps it would be worth documenting the required `transformIgnorePatterns`?

**Comment by angeloashmore** [comment]
Hey @mudge, glad to hear it's working!

I think it's a good idea to document this somewhere. I'll discuss this with the documentation team and see what we can do. 🙂
