### ISSUE TITLE
Fragment on Slice

### ISSUE THREAD

**Issue by RobinHerzog** [prismicio/prismic-gatsby#44]
Hi,

I'm looking for a solution to migrate to the new version.

I'm using a lot slice because I have page that repeat a lot. They are on different type.

To code less, I created fragement

```  
fragment articleFragment on PrismicDocument {
    data {
      bodyMain {
        slice_type
        primary {
          odd
          max_width_picture
          layout
          feature {
            text
          }
          article_image {
            url
          }
          article_title {
            text
            type
          }
          article_content {
            text
            type
          }
        }
      }
    }
  }

export const query = graphql`
  query getDocumentEngage($id: String!) {
    prismicDocument(id: { eq: $id }) {
      ...heroFragment
      ...statementFragment
      ...quoteFragment
      ...articleFragment
      ...articleCol2Fragment
      ...suggestedFeaturesFragment
      ...getInTouchFragment
    }
  }
`;
```

With the new version there is no PrismicDoucment.

Should I insert them as a variable instead ?

**Comment by anthonysapp** [comment]
You reference them as the document type on Prismic. 
IE a document with a type of "page" in your query would be: 

prismicPage(id: {eq:$id}){
	...
}

**Comment by RobinHerzog** [comment]
My Fragment are not duplicated per page or type. They are defined once in components.

**Comment by foresttoney** [comment]
I think I am working through the same issue.

Lets say that I have included a `Banner` slice on all my custom types. When building my templates, the exported query looks something like:

```
export const query = graphql`
  query Foo($uid: String!) {
    prismicFoo(uid: { eq: $uid }) {
      uid
      data {
        body {
          ... on PrismicFooBodyBanner {
            title {
              html
            }
          }
        }
      }
    }
  }
`
```

The problem is that I have to do the same when building a template for Bar and Baz. Naturally, I thought  I could just define a graphql fragment - which might look something like:

```
export const query = graphql`
  query Foo($uid: String!) {
    prismicFoo(uid: { eq: $uid }) {
      uid
      data {
        body {
          ... on PrismicFooBodyBanner {
            ...BannerSlice
          }
        }
      }
    }
  }
`
```

The problem I run into is that the related type is generated based on the Prismic type.

```
export const query = graphql`
  fragment BannerSlice on <generated_by_page> {
    title {
      html
    }
  }
`
```

It might be that I have only been working with Prismic and Gatsby for of all of a few days, but it is unclear to me how I can create reusable fragments for a given slice.

**Comment by RobinHerzog** [comment]
I found no answer. I had to duplicate sometimes my code :/

**Comment by angeloashmore** [comment]
The Gatsby/GraphQL type system is very strict, especially when it comes to fragments. As you explained, fragments must declare which type the fragment applies to.

For the `Banner` slice in `Foo`, `Bar`, and `Baz` custom types, each `Banner` is treated as a completely separate type. This must be done since there is no guarantee that `Banner` contains the same fields in each custom type. Furthermore, each field within the slice, despite having shared names and types, is also treated as an individual type. You'll see things like `field_22` and `field_23` even if `field` in both instances are of the same type but from different slices types.

Because of this, I don't believe there is a way to define a reusable fragment for slices. At least no easily with the current setup. It's possible we could define union types somehow, but I would need some help exploring that avenue.

**Comment by angeloashmore** [comment]
Gatsby's new schema customization might allow us to define interfaces. v3 of the plugin fully embraces schema customization so we can revisit once it is published.

It might look something like this in your `gatsby-node` file (100% untested):

```js
exports.sourceNodes = ({ actions: { createTypes } }) => {
  createTypes(`
    interface BannerSlice {
      title: PrismicStructuredTextType
    }

    type PrismicFooBodyBanner implements BannerSlice {}

    fragment BannerSliceFragment on BannerSlice {
      title {
        html
        text
      }
    }
  `)
}
```

**Comment by austonpramodh** [comment]
I am stuck on retrieving the Image in the body. 

Schema
```
{
  "Main": {
    "body": {
      "type": "Slices",
      "fieldset": "Slice zone",
      "config": {
        "labels": {
          "image": []
        },
        "choices": {
          "image": {
            "type": "Slice",
            "fieldset": "Image",
            "description": "Hello world",
            "icon": "broken_image",
            "display": "list",
            "non-repeat": {
              "image": {
                "type": "Image",
                "config": {
                  "constraint": {},
                  "thumbnails": [],
                  "label": "Image"
                }
              },
              "description": {
                "type": "Text",
                "config": {
                  "label": "description"
                }
              }
            },
            "repeat": {}
          }
        }
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/5049050/82730569-68242380-9d1e-11ea-84fd-ac6206bfc6b0.png)

I am not able to get the image as ImageSharp object.

**Comment by austonpramodh** [comment]
> I am stuck on retrieving the Image in the body.
> 
> Schema
> 
> ```
> {
>   "Main": {
>     "body": {
>       "type": "Slices",
>       "fieldset": "Slice zone",
>       "config": {
>         "labels": {
>           "image": []
>         },
>         "choices": {
>           "image": {
>             "type": "Slice",
>             "fieldset": "Image",
>             "description": "Hello world",
>             "icon": "broken_image",
>             "display": "list",
>             "non-repeat": {
>               "image": {
>                 "type": "Image",
>                 "config": {
>                   "constraint": {},
>                   "thumbnails": [],
>                   "label": "Image"
>                 }
>               },
>               "description": {
>                 "type": "Text",
>                 "config": {
>                   "label": "description"
>                 }
>               }
>             },
>             "repeat": {}
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> query that i am trying
> 
> ```
> query{
>   allPrismicCodePost{
>     totalCount
>     edges{
>       node{
>         id
>         data{
>           body{
>             ... on PrismicCodePostDataBody{
>               primary{
>                 ... on PrismicCodePostDataBodyPrimary{
>                   description
>                   image{
>                     url
>                   }
>                 }
>               }
>             }
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/5049050/82730569-68242380-9d1e-11ea-84fd-ac6206bfc6b0.png)
> 
> I am not able to get the image as ImageSharp object.

I missed the name of the schema which was supposed to be api-id.
![image](https://user-images.githubusercontent.com/5049050/82733135-7c245100-9d2f-11ea-9d42-91d72b176d16.png)
Sorry...my bad...

**Comment by angeloashmore** [comment]
No worries @austonpramodh, glad you figured out the issue.

By the way, you shouldn't need to use `... on PrismicCodePostDataBodyPrimary` on line 11 of your query. Just the `... on PrismicCOdePostDataBody` on line 9 is required.

**Comment by austonpramodh** [comment]
> No worries @austonpramodh, glad you figured out the issue.
> 
> By the way, you shouldn't need to use `... on PrismicCodePostDataBodyPrimary` on line 11 of your query. Just the `... on PrismicCOdePostDataBody` on line 9 is required.

Yeah... just figured it out... Thank you so much...

**Comment by kb1995** [comment]
@angeloashmore I'm trying to implement this into my current website while upgrading to v4. I have a lot of shared slices, so if I change a Slice structure, I takes me quite a lot of time to duplicate across all custom types - so utilising Fragments will be great. Is it possible if we get a working example in the docs for this?

**Comment by angeloashmore** [comment]
Hey @kb1995, creating interfaces and fragments for shared Slices is very fragile and not recommended, nor supported. As such, there isn't an example to share or a recommended practice.

I agree that it would be beneficial for situations like yours so I can help debug your case.

Your fragment appears to be placing the fields in the wrong type. `PrismicCustomerPageDataBodyImage` is a Slice, but the actual content fields are nested within `primary` or `items`. You could do something like the following, depending on how you have your Slice configured:

```javascript
exports.sourceNodes = ({ actions: { createTypes } }) => {
  createTypes(`
    interface ImageSlice {
      primary: ImageSlicePrimary
    }

    interface ImageSlicePrimary {
      lightbox_white_bg: Boolean
      caption: PrismicStructuredTextType
      image: PrismicImageType
    }

    type PrismicCustomerPageDataBodyImage implements ImageSlice {}
    type PrismicCustomerPageDataBodyImagePrimary implements ImageSlicePrimary {}
  `)
}
```

I would recommend moving the fragment into its own file as well.

```javascript
// src/fragments.js

import { graphql } from 'gatsby'

export const ImageSliceFragment = graphql`
  fragment ImageSliceFragment on ImageSlice {
    primary {
      ... on ImageSlicePrimary {
        lightbox_white_bg
        caption
        image
      }
    }
  }
`
```

**Comment by angeloashmore** [comment]
I'm going to close this old issue as it is not something that will be added to the plugin. Instead, Shared Slices will provide this functionality once Slice Machine is supported.
