### ISSUE TITLE
Previews working locally but not on a staging environment

### ISSUE THREAD

**Issue by nooxx** [prismicio/prismic-gatsby#444]
Hi, I've got the previews working locally but when trying on a staging environment the preview page gets stuck on /preview and doesn't redirect.

There is this error in the console:

<img width="654" alt="Screenshot 2021-09-06 at 10 06 36" src="https://user-images.githubusercontent.com/6512445/132183725-2e5b5166-4790-46cb-a94f-082675538287.png">

### Versions

- gatsby-source-prismic: 4.1.2
- gatsby-plugin-prismic-previews: 4.1.3
- node: 14.16.1

### Reproduction
Prismic previews config:
<img width="1048" alt="Screenshot 2021-09-06 at 10 21 37" src="https://user-images.githubusercontent.com/6512445/132184806-2874fb84-3442-4b0c-ba49-9c18471775b5.png">

Plugin config:
```js
{
      resolve: "gatsby-source-prismic",
      options: {
        repositoryName: process.env.GATSBY_PRISMIC_REPOSITORY,
        accessToken: process.env.GATSBY_PRISMIC_TOKEN,
        // Get the correct URLs in blog posts
        linkResolver: (doc) => {
          if (doc.type === "posts") {
            return `/blog/post/${doc.uid}`
          }

          return `/`
        },
        schemas: {
          posts: require("./src/schemas/posts.json"),
        },
      },
    },
    {
      resolve: 'gatsby-plugin-prismic-previews',
      options: {
        repositoryName: process.env.GATSBY_PRISMIC_REPOSITORY,
        accessToken: process.env.GATSBY_PRISMIC_TOKEN,
      },
    },
```

My preview.js:
```js
import * as React from "react"
import { withPrismicPreviewResolver } from "gatsby-plugin-prismic-previews"
import { linkResolver } from "../linkResolver"


const PreviewPage = () => {
  return (
    <div>
      <p>Loading preview...</p>
    </div>
  )
}

export default withPrismicPreviewResolver(PreviewPage, [
  {
    repositoryName: process.env.GATSBY_PRISMIC_REPOSITORY,
    linkResolver,
  },
])
```

My 404.js:
```js
import BlogPostTemplate from "../pages/blog/post/{PrismicPosts.uid}";
import { linkResolver } from "../linkResolver"

const PageNotFound = () => {
  return (
    <div>
      ...
    </div>
  )
}
export default withPrismicUnpublishedPreview(PageNotFound, [
  {
    repositoryName: process.env.GATSBY_PRISMIC_REPOSITORY,
    linkResolver,
    componentResolver: componentResolverFromMap({
      posts: BlogPostTemplate,
    }),
  },
])
```

Thanks for your help.

**Comment by angeloashmore** [comment]
Hey @nooxx, that error comes from the Prismic toolbar. It seems to be a result of Chrome extensions interfering with the toolbar's setup process. You can see more details here: https://github.com/prismicio/prismic-toolbar/issues/60#issuecomment-887604685

I fix for the toolbar error was written but it has not been merged yet.

Are you able to test previews in incognito mode without extensions?

**Comment by nooxx** [comment]
@angeloashmore There is no error in incognito mode indeed. However I still see a blank page on /preview.

**Comment by angeloashmore** [comment]
Ah, okay, at least we can rule out the toolbar as the issue.

Everything you posted looks normal. Since it is working locally, your code should be correct.

On your staging site, could you perform the following?

- Verify that your environment variables are up to date (`GATSBY_PRISMIC_REPOSITORY`, `GATSBY_PRISMIC_TOKEN`).
- Clear the build cache and rebuild the site.

If it still does not work, it might be easiest to figure out the issue if I can look at your code and Prismic repository. In that case, could you send me a private message on the Prismic community forum?

To send me a message: https://community.prismic.io/new-message?username=angeloashmore&title=GitHub%20Issue%20422

**Comment by nooxx** [comment]
So the issue comes from the link resolver config within prismic, when hosting on AWS, you must set it to "/preview/" with a trailing slash.

Apparently AWS removes query parameters when URL doesn't have a trailing slash and that causes the redirect to fail.
