### ISSUE TITLE
Unpublished documents possibly remain in Gatsby's cache

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-gatsby#445]
### Versions

- gatsby-source-prismic: v4.1.2
- gatsby-plugin-prismic-previews: N/A
- node: v14.17.0

### Reproduction

N/A (will create one when diagnosing the issue)

### Steps to reproduce

1. Publish a document.
2. Build the site.
3. Unpublish the document.
4. Rebuild the site.
5. See that the unpublished page may still be present in the Gatsby build.

To remove the unpublished page, Gatsby's cache must be cleared.

### What is expected?

Unpublishing a document removes the node from Gatsby.

### What is actually happening?

Unconfirmed - The unpublished document's node remains in the Gatsby cache.

**Comment by iriepixel** [comment]
Hi @angeloashmore 
I spoke to Simon and reported this issue. We are not sure is it Prismic or Gatsby. How can I help you with investigation? What information do you need from me?

**Comment by angeloashmore** [comment]
Hey @iriepixel, I just tried the *Steps to reproduce* above and everything thing worked as expected:

1. Publish a document.
2. Build the site.
3. Unpublish the document.
4. Rebuild the site.
5. The unpublished document's page is gone.

Based on this, my initial guess is that it could be related to one of the following:
- Gatsby Cloud's caching or incremental builds (if you use Gatsby Cloud), or
- Pages being created using hardcoded routes or queries

Could you share the following details?

1. Are you using Gatsby Cloud, Netlify, or a different host?
2. How are you creating your pages?
  - Programmatically in `gatsby-node.js` and [`createPage`](https://www.gatsbyjs.com/docs/recipes/pages-layouts#creating-pages-programmatically-with-createpage)?
  - Manually as individual files in `src/pages`?
  - Automatically using the [File System Route API](https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/) files in `src/pages` using

If you are using `gatsby-node.js` to create pages, could you share your `gatsby-node.js` file?

If you are using files in `src/pages`, could you share those files and their filenames as well?

If you want to share these files in private, you can send me a message on the Prismic community forum here: https://community.prismic.io/new-message?username=angeloashmore&title=GitHub%20Issue%20445

Thanks!

**Comment by iriepixel** [comment]
Hi @angeloashmore ,

Thank you for your reply.

You are absolutely right. I'm using Gatsby Cloud and this issue is only happens when incremental build triggered by webhook from Prismic. Once I clear cache and trigger build command manually on Gatsby Cloud the issue is gone. Here is what I use:

1. Gatsby Cloud
2. I'm creating pages automatically in `gatsby-node` and `createPage`

I've sent you file privately on Prismic forum.

Please let me know if you need more details for your investigation.

Thank you,
Jev

**Comment by angeloashmore** [comment]
Thanks for the details! It sounds like the plugin is not correctly deleting the node when aggressive caching is enabled (such as on Gatsby Cloud).

I'll need to test things out and will likely require a small plugin update. I will let you know once I learn more and find a fix. Thanks!

**Comment by iriepixel** [comment]
@angeloashmore Thank you!

**Comment by heart-of-code** [comment]
I'm experiencing a similar issue with Custom Types

1. archived and deleted Custom Type in prismic.io
  - note: a pre-requisite to fully delete a Custom Type is to delete all of the Document instances of that type
2. remove now-unused schemas from gatsby-config.js
3. run `gatsby build`

expected:
build successfully, no longer using the removed Custom Types

actual:
receive error `JSON schema for "[type]" is missing`

workaround:
providing an empty schema (below) circumvents the error and allows builds to proceed
```
{
  "Main": {}
}
```

**Comment by heart-of-code** [comment]
Ah, well thank you for clearing that up! 🙌

**Comment by benjaminwaterlot** [comment]
Hey @angeloashmore, just wanna feedback that we encounter the same problem with unpublishing documents.

They systematically seem to remain through the Gatsby Cloud incremental build and we have to trigger a build manually each time we want to unpublish something.

**Comment by angeloashmore** [comment]
Thanks @benjaminwaterlot, I was able to reproduce this issue myself as well.

I spoke with someone on the Gatsby team about the issue. It is a Gatsby Cloud-specific issue with sending webhooks to the plugin and they are working on a fix. Once I hear back from them, I'll post here.

**Comment by angeloashmore** [comment]
@iriepixel @benjaminwaterlot This has been resolved by the Gatsby team and required as small fix to `gatsby-source-prismic`.

Could you update to `gatsby-source-prismic@4.1.6` and try it out? I'll close the issue but let me know if anything goes wrong.

Thanks!
