### ISSUE TITLE
Document how to provide deleted Custom Type schemas

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-gatsby#446]
### Is your feature request related to a problem? Please describe.

Custom Types that have been used at least once and deleted still need to be provide to the plugin. This is required because the Prismic API returns a list of all Custom Types for a repository, including deleted ones.

The official way to address this is to provide an empty object (`{}`) as the schema like the following example:

```ts
// gatsby-config.js

module.exports = {
  plugins: [
    {
      resolve: 'gatsby-source-prismic',
      options: {
        schemas: {
          my_deleted_schema: {}
        }
      }
    }
  ]
}
```

### Describe the solution you'd like

This should be documented on the official docs (https://prismic.io/docs/technologies/install-the-plugin-gatsby).

The error message that appears for missing schemas should also mention how to address this. The plugin currently prints the following message:

```
JSON schema for "[type]" is missing
```

### Describe alternatives you've considered

N/A

### Additional context

https://github.com/prismicio/prismic-gatsby/issues/445#issuecomment-918477652

**Comment by Coffee-Up** [comment]
I have adressed them this issue, they told me that they will work on it.

**Comment by angeloashmore** [comment]
This is included as part of V5. The following message will be printed if a missing schema is found:

```
JSON model for "%s" is missing. If the Custom Type is no longer in use, you may provide "{}" as the JSON model.
```
