### ISSUE TITLE
After enabling `transformFieldName`, I get 'Cannot return null for non-nullable field'

### ISSUE THREAD

**Issue by kilinkis** [prismicio/prismic-gatsby#447]
### Versions

- gatsby-source-prismic: 4.0.2 (also tried with latest stable 4.1.2)
- gatsby-plugin-prismic-previews: 4.0.2 (also tried with latest stable 4.1.3)
- node: v14.16.0

### Reproduction

```tsx
import camelCase from 'camelcase'

// ...
customTypesApiToken: process.env.PRISMIC_CUSTOM_TYPES_API_TOKEN,
transformFieldName: camelCase,
```

### Steps to reproduce
1. Enable `transformFieldName` flag.
2. Start dev server and run a query like this:
```
query BlogTags {
  allPrismicBlogPost {
    nodes {
      first_publication_date
    }
  }
}
```

### What is expected?
1. All fields are converted
2. Data to be returned normally (see this screenshot without `transformFieldName`):
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/133504/133448587-014b590f-d412-4deb-8e6f-3498c9e62721.png">

### What is actually happening?

First of all, these fields are not transforming
<img width="274" alt="image" src="https://user-images.githubusercontent.com/133504/133446559-845ffadf-49c5-4c36-8553-3b95b87f200a.png">

Second of all, graphql throws this error 
<img width="761" alt="image" src="https://user-images.githubusercontent.com/133504/133446749-67664ddd-a568-4268-8dc3-e4176befc9bc.png">

Let me know if you need me to add more context or have any doubts. Thanks!

**Comment by angeloashmore** [comment]
Hi @kilinkis, thanks for providing these details.

The `transformFieldName` option will only transform fields within `data`. These are fields that are defined by your Custom Types, which may contain invalid GraphQL names (like `my-field` with a dash). Fields outside `data`, like `first_publication_date`, are left as is from the Prismic API.

You should not see the "Cannot return null for non-nullable field" error, however. I will test this and let you know what I find.

Thanks!

**Comment by angeloashmore** [comment]
@kilinkis Could you try the latest version of `gatsby-source-prismic`, `v4.1.5`?

There was a bug where all documents fields were transformed using the `transformFieldName` function, including `first_publication_date`. It has been fixed to only transform the `data` field.

**Comment by kilinkis** [comment]
thanks for the answers @angeloashmore, will try that version in the morning (Europe) :)

**Comment by kilinkis** [comment]
hi @angeloashmore updating to that version did the trick :) thanks for your reply!

**Comment by angeloashmore** [comment]
Haha awesome, glad to hear it works! 😄
