### ISSUE TITLE
Vimeo thumbnail changed

### ISSUE THREAD

**Issue by rundas912** [prismicio/prismic-gatsby#455]
Hello :) 

After upgrading my site to gatsby v3 and upgrading your plugin to the latest version (from 3.3.1. to 4.1.7) it looks like I don't receive the right thumbail urls from my vimeo videos anymore.

For example, after setting up an embed field in prismic with my video, here is the url I used to get for my thumbnail : 
"https://i.vimeocdn.com/video/1069849511-51e95ff2ecee8c1053490881fca35cc18b5a5d1999c14593d76374258f5835cc-d_640"

With the updated plugins, here is what I get : 
"https://i.vimeocdn.com/video/1069849684_640"

### Versions

- gatsby-source-prismic: 4.1.7
- gatsby : 3.14.0
- node : 15.0.1

### Reproduction

Here is my query and the results I used to get before upgrading

![Capture d’écran 2021-10-04 à 13 41 34](https://user-images.githubusercontent.com/43321466/135845498-57f24227-9538-4f8a-9302-3fa34170df25.png)

Please let me know if you need any more precisions :)

**Comment by angeloashmore** [comment]
Hi @rundas912, I apologize for the very late reply!

You may have learned about this already, but Vimeo recently changed the way thumbnail URLs are provided. Basically, it seems like you now need to make an additional API call to get a thumbnail. I'm having trouble finding a clear way of doing this, but I believe the steps are provided here: https://developer.vimeo.com/api/upload/thumbnails

I found others with the same problem on Twitter. You might find more information there: https://twitter.com/search?q=vimeo%20thumbnail%20url&src=typed_query&f=live
