### ISSUE TITLE
Don't load preview iframes if not in a preview

### ISSUE THREAD

**Issue by kb1995** [prismicio/prismic-gatsby#458]
Hey Angelo,

Once again, thanks for the awesome work and I like what you are doing with v5.

I've been doing some performance optimisations for a client's Gatsby website and I noticed that there is an `iframe` which is being loaded on page load - from the looks of it without a `defer`.

It takes ~340ms which is 7x more than my next longest file on page load.

Can we either add a defer load on this or not load it at all considering that I'm not in a preview.

Any advice that can help me in the meantime is also greatly appreciated!

<img width="961" alt="Screenshot 2021-10-07 at 16 39 18" src="https://user-images.githubusercontent.com/32920882/136417760-b874b42b-d44c-4089-9ce5-a3eb6126c645.png">

**Comment by OleksandrRakovets** [comment]
I will vouch for such improvement -- just came in to post a similar issue.

`toolbar.js` weighs a 1/4 of scripts on my website (another 1/2 is GA & GTM though 😒). It would be great to limit its loading to editors from all visitors.

Our editors use *.netlify.app mirror not to interfere with analytics on the public domain. I hoped to only enable preview script on that domain, but Gatsby does not provide such control in the single deploy.

**Comment by OleksandrRakovets** [comment]
Hi @angeloashmore!

Is there any progress on lazy-loading?

I have attempted to hide `gatsby-plugin-prismic-previews` config and `withPrismicPreview` wrapper behind a `process.env` flag in order to deploy a separate preview subdomain.

Even though I managed to override default exports in Gatsby pages, webpack (or babel, not really sure here) still loads the package into bundle, because it must be imported at the top of pages 😞

**Comment by kb1995** [comment]
Hey @angeloashmore - any updates on this?

**Comment by angeloashmore** [comment]
Hey @kb1995, I'm going through old issues and saw you didn't get a response. Sorry about that! The Prismic toolbar and its iframe is required to detect whether or not a preview session is active, so it must be active even outside preview sessions.

In the latest version of `gatsby-plugin-prismic-previews`, preview-related code is lazy-loaded except the Prismic toolbar. That should reduce bundle sizes and speed up initial page loads.
