### ISSUE TITLE
Add setting to allow schemas array to be non-exhaustive for gatsby-source-prismic

### ISSUE THREAD

**Issue by larsenwork** [prismicio/prismic-gatsby#459]
### Is your feature request related to a problem? Please describe.

When adding a new custom type in prismic our site becomes non-buildable until we update options for `gatsby-source-prismic` in our `gatsby-config` to contain that schema.

### Describe the solution you'd like

Something like this: 

```diff
    {
      resolve: 'gatsby-source-prismic',
      options: {
        schemas: {
          'custom-one': require('../schemas/custom-one.json'),
        },
+ 		exhaustiveSchemas: false,
        repositoryName: 'omhu',
      },
    },
```

That would make the plugin not fail even if I added e.g. `custom-two` type in prismic.

### Describe alternatives you've considered

—

### Additional context

https://github.com/prismicio/prismic-gatsby/blob/72d6a6860262293d3ade374387ac9ffa07b629da/packages/gatsby-source-prismic/src/plugin-options-schema.ts#L107-L175

**Comment by angeloashmore** [comment]
I'm going to close this issue as the Custom Types API is the recommended solution to always having the latest Custom Types in your project.

Feel free to comment here if you want to continue the discussion and I can reopen it. Thanks!

**Comment by larsenwork** [comment]
Thanks, sorry — we migrated to using the `custom types api` and it works just fine 👍

**Comment by angeloashmore** [comment]
Awesome, no worries! Glad to hear it works!
