### ISSUE TITLE
Invalid API Response was returned due to invalid plugin configuration

### ISSUE THREAD

**Issue by AntoninBarbier** [prismicio/prismic-gatsby#461]
Hello everyone,

I'm new to Gatsby and Prismic and I can't figure out how to make this plugin work.
I followed this documentation
https://prismic.io/docs/technologies/install-the-plugin-gatsby 
and this one
https://www.gatsbyjs.com/docs/how-to/sourcing-data/sourcing-from-prismic/
and I did the following:
- created my API token using the Prismic interface
- installed the plugin with `npm install gatsby-source-prismic`
- filled my plugin configuration inside `gatsby-config.js`
- created a folder at the root of my project named custom_types to store the json files for each one of the custom type I created in Prismic, making sure the filenames are similar to the API_ID
- ran `npm run start` and got the following error:
           ERROR #11331  PLUGIN
          Invalid plugin options for "gatsby-source-prismic":
          - An invalid API response was returned
          not finished open and validate gatsby-configs, load plugins - 16.930s

Here is my plugin configuration (generic values used for this bug report for confidential reasons)
```
{
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: `my-repo-name`,
        accessToken: `my-api-key`,
        schemas: {
          homepage: require("./custom_types/homepage.json"),
          destination: require("./custom_types/destination.json"),
          lieu: require("./custom_types/lieu.json"),
          region: require("./custom_types/region.json"),
          route: require("./custom_types/route.json"),
          type_de_voyage: require("./custom_types/type_de_voyage.json"),
        },
     },
},
```

I also tried to use the Custom Types API to automatically retrieve my schemas using the customTypesApiToken, but I was still having the error.

It doesn't seem like I did anything wrong, did I?

### Versions

- gatsby-source-prismic: ^4.2.0
- node: v14.18.1
- npm: v6.14.15

**Comment by angeloashmore** [comment]
Hey @AntoninBarbier, I haven't heard back on https://community.prismic.io/. I tested your repository name and access token successfully so I'm not sure what the error is. Could you double check that they are being passed correctly in `gatsby-config.js`?

I'm going to close this issue as it should be working. If you are still experiencing this issue, please let me know and I can take a look again.
