### ISSUE TITLE
Preview not working on v5

### ISSUE THREAD

**Issue by marcomiduri** [prismicio/prismic-gatsby#464]
### Versions

- gatsby-source-prismic: ^5.0.0-next.11
- gatsby-plugin-prismic-previews: ^5.0.0-next.10
- node: v16.3.0

### Reproduction
If you click preview icon on prismic website, it opens localhost and goes to /preview URL first. After that it goes to the specific page but it loads a lot of data from search query. After a while, it shows error to me.

- gatsby-config.js
```javascript
    {
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: repositoryName,
        accessToken: `${process.env.GATSBY_PRISMIC_API_KEY}`,
        linkResolver: doc => linkResolver(doc),
        schemas: {
          page: require('./src/schemas/page.json'),
          post: require('./src/schemas/post.json'),
          author: require('./src/schemas/author.json'),
          news_links: {},
        },
      },
    },
    {
      resolve: 'gatsby-plugin-prismic-previews',
      options: {
        repositoryName: repositoryName,
        accessToken: process.env.GATSBY_PRISMIC_API_KEY,
        toolbar: 'new',
      },
    }
```
### What is actually happening?

I created a new content type `new_links` and added a document there. Right now, we are not using this content type so I add it to the schemas in `gatsby-config.js` like this.

When the preview happens, it compares the response with content type but the response is a valid object and content type is defined as an empty object `{}`. Because of this unmatched case, we are getting the error.

Of course, I believe this issue can be resolved if I use the automatic content type method using `customTypesApiToken`.

```javascript
    {
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: repositoryName,
        accessToken: `${process.env.GATSBY_PRISMIC_API_KEY}`,
        linkResolver: doc => linkResolver(doc),
        schemas: {
          page: require('./src/schemas/page.json'),
          post: require('./src/schemas/post.json'),
          author: require('./src/schemas/author.json'),
          news_links: {},
        },
      },
    },
```

Error: No type for path: news_links.data. Did you register the Custom Type model?

./node_modules/gatsby-source-prismic/dist/index.cjs:369
```javascript
  367 |   const type = config.getTypePath(config.path);
  368 |   if (!type) {
> 369 |     throw new Error(`No type for path: ${config.path.join(".")}. Did you register the Custom Type model?`);
  370 |   }
  371 |   switch (type.type) {
  372 |     case exports.PrismicSpecialType.Document: {
```

**Comment by angeloashmore** [comment]
Hey @marcomiduri, `schemas` should always match what is present in Prismic. The empty object schema is supported only for Custom Types that have been deleted.

You can copy the JSON file in the project and `require()` it like the others. If you use the Custom Types API via `customTypesApiToken`, this will be done for you automatically.

I recommend using the Custom Types API as it will always have the latest content models automatically.

I'm going to close this issue since this is working as expected, but we can continue the discussion here and reopen it if necessary. Thanks!
