### ISSUE TITLE
styles.css is not exported from package

### ISSUE THREAD

**Issue by jodiedoubleday** [prismicio/prismic-gatsby#467]
### Versions

- gatsby-source-prismic: 5.0.0
- gatsby-plugin-prismic-previews: 5.0.0
- node:14.17.3

### Steps to reproduce
Update to Gatsby v4 and Prismic  5.0.0 (fantastic work on getting that out so quickly) and running any application as normal `gatsby develop`

### What is expected?
The build to complete successfully and Prismic CSS files to resolve.

### What is actually happening?
` ModuleNotFoundError: Module not found: Error: Package path ./dist/styles.css is not exported from package /node_modules/gatsby-plugin-prismic-previews )`
I am including `import 'gatsby-plugin-prismic-previews/dist/styles.css'` in both `gatsby-browser` and `gatsby-ssr`

(will try and make a minimal repo asap and add to this bug report)

**Comment by angeloashmore** [comment]
An empty CSS file has been added in `v5.0.1`. It will be removed in `v6.0.0`.
