### ISSUE TITLE
Preview of unpublished page results in a Runtime.ImportModuleError error

### ISSUE THREAD

**Issue by kb1995** [prismicio/prismic-gatsby#469]
### Versions

- gatsby-source-prismic: ^5.0.0
- gatsby-plugin-prismic-previews: ^5.0.0
- node: v14

### Steps to reproduce

- Configure Previews as explained in https://prismic.io/docs/technologies/previews-gatsby
- Deploy to Netlify in a preview branch
- Set up preview of that branch on Prismic
- Attempt to preview an unpublished document (previews work without a problem for published documents with changes)

### What is expected?

See the preview of an unpublished document. The preview of an unpublished document works in development

### What is actually happening?

Get the following error message:

```
{
"errorType": "Runtime.ImportModuleError",
"errorMessage": "Error: Cannot find module '/var/task/.cache/page-ssr'\nRequire stack:\n- /var/task/.netlify/functions-internal/__dsg/__dsg.js\n- /var/task/__dsg.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
"trace": [
"Runtime.ImportModuleError: Error: Cannot find module '/var/task/.cache/page-ssr'",
"Require stack:",
"- /var/task/.netlify/functions-internal/__dsg/__dsg.js",
"- /var/task/__dsg.js",
"- /var/runtime/UserFunction.js",
"- /var/runtime/index.js",
"    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
"    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
"    at Object.<anonymous> (/var/runtime/index.js:43:30)",
"    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
"    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
"    at Module.load (internal/modules/cjs/loader.js:937:32)",
"    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
"    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
"    at internal/main/run_main_module.js:17:47"
]
}
```

**Comment by angeloashmore** [comment]
Hey @kb1995, are you using Gatsby 4's DSG or SSR rendering methods?

**Comment by kb1995** [comment]
> Hey @kb1995, are you using Gatsby 4's DSG or SSR rendering methods?

@angeloashmore No, just using the generic way of creating dynamic pages - the same method I'm using for another Gatsby website which is currently on Gatsby 3/ prismic-gatsby v4

Here is my `gatsby-node.js` if that helps:

```
// Create blog pages dynamically
exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions

  // ================ Prismic ================
  const pages = await graphql(`
    query {
      allPrismicContentPost {
        nodes {
          id
          uid
          type
          url
          data {
            category {
              document {
                ... on PrismicCategory {
                  uid
                }
              }
            }
          }
        }
      }
      allPrismicCaseStudy {
        nodes {
          id
          uid
          type
          url
        }
      }
    }
  `)

  pages.data.allPrismicContentPost.nodes.forEach((page) => {
    createPage({
      path: linkResolver(page),
      component: path.resolve(__dirname, 'src/templates/post.tsx'),
      context: {
        id: page.id,
        categoryUid: page.data.category.document?.uid,
      },
    })
  })

  pages.data.allPrismicCaseStudy.nodes.forEach((page) => {
    createPage({
      path: linkResolver(page),
      component: path.resolve(__dirname, 'src/templates/case-study.tsx'),
      context: {
        id: page.id,
      },
    })
  })
}
```

**Comment by kb1995** [comment]
Small update - I just realised that a non-prismic 404 page also gives this error. Seems to be related to Netlify Functions, as my 404/previews work in development/local builds.

I will follow up once I have more info

**Comment by angeloashmore** [comment]
Thanks @kb1995, I'll look out for your follow up if you find anything.

In the mean time, I noticed your `withPrismicUnpublishedPreview` function isn't being provided any repository configuration objects. Do you have it setup in `<PrismicPreviewProvider>` instead? Just checking to make sure this isn't the issue.

**Comment by kb1995** [comment]
@angeloashmore Thanks for the follow up, yes, I have those provided in PrismicPreviewProvider in both gatsby-browser and gatsby-ssr

I submitted a ticket to Netlify Support - https://answers.netlify.com/t/gatsby-4-runtime-importmoduleerror-on-404-pages/46608/2

**Comment by angeloashmore** [comment]
Ah, good to know. Thank you for figuring out what was going on. Hopefully the updated Netlify plugin fixes this issue.
