### ISSUE TITLE
The Route Resolver in Gatsby?

### ISSUE THREAD

**Issue by kb1995** [prismicio/prismic-gatsby#478]
In Nextjs, we have access to https://prismic.io/docs/technologies/the-route-resolver-nextjs which allows us to create a nested url.

A standard use case is having a BlogPost custom type which is linked to a category. So it would allow you to build URLs such as

`/[category.uid]/[blog-post.uid]`

Is this possible in the current prismic-gatsby plugin? Sorry if it is, I just couldn't find it in the documentation. I remember that it was possible in the old gatsby graphql prismic plugin (I used it to build https://fullstackheroes.com/) but currently I'm migrating over to the new prismic plugin, so just figuring how I could handle that case.

Thanks!

**Comment by angeloashmore** [comment]
Hey @kb1995, good question. Route Resolvers were not supported in the source and preview plugins, but I just merged and published support for them.

A `routes` option is now available where you can provide your Route Resolver objects.

An example is included in the PR here: https://github.com/prismicio/prismic-gatsby/pull/479

Support is included as of these versions:
- `gatsby-source-prismic`: `v5.2.0`
- `gatsby-plugin-prismic-previews`: `v5.2.0`

Thanks for bringing this up!

---

As an aside, you can handle nested links like your example using a [Link Resolver](https://prismic.io/docs/core-concepts/link-resolver-route-resolver) as well. You would need to write a Link Resolver and provide a `fetchLinks` option like this:

```js
// gatsby-config.js

module.exports = {
  plugins: [
    {
      resolve: "gatsby-source-prismic",
      options: {
        repositoryName: 'repo-name',
        fetchLinks: ['blog_post.category'],
        linkResolver: (doc) => {
          if (doc.type === 'blog_post') {
            return `/${[doc.data.category?.uid, doc.uid].join('/')}`
          }

          return `/${doc.uid}`
        },
      },
    },
  ],
};
```
