### ISSUE TITLE
env.prismicClient.getAll is not a function 

### ISSUE THREAD

**Issue by maheshsamudra** [prismicio/prismic-gatsby#480]
### Versions

- gatsby-source-prismic: v5.2.0
- gatsby: v4.1.2
- node: v14.17.6 
- on Windows 10

### Reproduction

1. Install a fresh copy of gatsby using `npm init gatsby` without any other packages
2. Install `gatsby-source-prismic` and `gatsby-plugin-image`
3. Linked the JSON schemas manually.
4. `npm run develop` or `npm run build`

### Displayed error
```
"gatsby-source-prismic" threw an error while running the sourceNodes lifecycle:
env.prismicClient.getAll is not a function

TypeError: env.prismicClient.getAll is not a function
- queryAllDocuments.ts:28
[project-path]/[gatsby-source-prismic]/src/lib/queryAllDocuments.ts:28:22
```

<details close>
<summary>Additional Details</summary>
<br>

package.json file:

```
{
  "name": "ws-ma",
  "version": "1.0.0",
  "private": true,
  "description": "ws-ma",
  "author": "Mahesh Samudra",
  "keywords": [
    "gatsby"
  ],
  "scripts": {
    "dev": "gatsby develop",
    "start": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve",
    "clean": "gatsby clean"
  },
  "dependencies": {
    "gatsby": "^4.1.2",
    "gatsby-plugin-image": "^2.1.0",
    "gatsby-source-prismic": "^5.2.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
}
```

gatsby-config.js

```
module.exports = {
  siteMetadata: {
    siteUrl: "https://www.yourdomain.tld",
    title: "ws-ma",
  },
  plugins: [
    "gatsby-plugin-image",
    {
      resolve: 'gatsby-source-prismic',
      options: {
        accessToken: "access_token_from_prismic",
        repositoryName: "repository_name",
        schemas: {
          home_page: require('./src/schemas/home_page.json'),
          testimonials: require('./src/schemas/testimonials.json')
        }
      },
    },
  ],
};

```
</details>

### What is expected?
It should fetch the posts from Prismic. But for `npm run develop` the development server starts without any data from Prismic. `npm run build` fails because of this error.

### What is actually happening?
When queyAllDocuments file is observed, my IDE says: `TS2339: Property 'getAll' does not exist on type 'Client'.`

**Comment by jodiedoubleday** [comment]
I have just experienced the same issue while updating to v5.2.0.
Just trying to roll back to earlier versions to see if i can get things working again.

**Comment by DennisKraaijeveld** [comment]
Having the same. Which is weird. At first everything worked fine. I think it has to do with Gatsby 4.1

**Comment by angeloashmore** [comment]
Quick background info: `@prismicio/client`, the JavaScript client used for interacting Prismic's REST API, recently changed its `getAll` method to `dangerouslyGetAll`. The Gatsby plugins use `getAll` to fetch all documents from a Prismic repository when starting the development server or building the project.

The plugins are now updated to use the new method name.

**Comment by maheshsamudra** [comment]
> Hey everyone, sorry about that! Upgrade to `v5.2.1` and this will be fixed:
> 
> * `gatsby-source-prismic`: `v5.2.1`
> * `gatsby-plugin-prismic-previews`: `v5.2.1`

This works!
