### ISSUE TITLE
PrismicPreviewProvider in gatsby-ssr.js causes builds to fail in Gatsby V4

### ISSUE THREAD

**Issue by justinluttrell** [prismicio/prismic-gatsby#485]
I'm updating my Prismic plugins to v5 as described in the [migration guide](https://prismic.io/docs/technologies/gatsby-prismic-v4-to-v5#update-gatsby). After following all the steps in the guide my builds are now failing. With some debugging I've narrowed down the cause of failures to the use of `<PrismicPreviewProvider>` component in my `gatsby-ssr.js` file. When commenting out this component, the builds succeed. However, previews hang and no longer work, so this isn't a viable solution/fix. 

I've tried passing the new `repositoryConfigs` props to the provider component but this doesn't seem to help. 

### Versions
- gatsby: v4
- gatsby-source-prismic: v5.2.3 
- gatsby-plugin-prismic-previews: 5.2.1 
- node: v14.18.1

### Reproduction
This is a private repo/project so it is difficult to put together a minimal reproduction.

### Steps to reproduce
Migrate a Gatsby 3 project that uses v4 Prismic Plugins to Gatsby 4 and Prismic V5 plugins.

### What is expected?

As of now, this project supports previews for published and unpublished docs, along with components that use static queries (by use of `useMergePrismicPreviewData`). I expect these would all continue to work after migrating to Gatsby 4 and Prismic V5. 

### What is actually happening?

The builds consistently fail with either:

```bash
Maximum call stack size exceeded

  RangeError: Maximum call stack size exceeded
  
  - RegExp.exec
  
  - source-map-support.js:174 retrieveSourceMapURL
    [gatsby-frontend]/[source-map-support]/source-map-support.js:174:21
  
  - source-map-support.js:186 Array.<anonymous>
    [gatsby-frontend]/[source-map-support]/source-map-support.js:186:26
  
  - source-map-support.js:85 
    [gatsby-frontend]/[source-map-support]/source-map-support.js:85:24
  
  - source-map-support.js:216 mapSourcePosition
    [gatsby-frontend]/[source-map-support]/source-map-support.js:216:21
  
  - source-map-support.js:397 wrapCallSite
    [gatsby-frontend]/[source-map-support]/source-map-support.js:397:20
  
  - source-map-support.js:446 Function.prepareStackTrace
    [gatsby-frontend]/[source-map-support]/source-map-support.js:446:39
  
  - errors.js:127 maybeOverridePrepareStackTrace
    internal/errors.js:127:29
  
  - errors.js:106 prepareStackTrace
    internal/errors.js:106:5
  
  - stack-trace.js:21 Object.exports.parse
    [gatsby-frontend]/[stack-trace]/lib/stack-trace.js:21:12
  
  - construct-error.js:41 constructError
    [gatsby-frontend]/[gatsby-cli]/lib/structured-errors/construct-error.js:41:95
  
  - reporter.js:176 Reporter.error
    [gatsby-frontend]/[gatsby-cli]/lib/reporter/reporter.js:176:57
  
  - reporter.js:103 Reporter.panic
    [gatsby-frontend]/[gatsby-cli]/lib/reporter/reporter.js:103:32
  
  - build.ts:223 build
    [gatsby-frontend]/[gatsby]/src/commands/build.ts:223:14
```

OR

```bash
ERROR 

extendStatics is not a function

  TypeError: extendStatics is not a function
  
  - render-page.js:55346 __extends
    /Users/me/dev/gatsby-frontend/.cache/page-ssr/routes/render-page.js:55346:5
  
  - render-page.js:54344 
    /Users/me/dev/gatsby-frontend/.cache/page-ssr/routes/render-page.js:54344:28
  
  - render-page.js:54344 Object.2099
    /Users/me/dev/gatsby-frontend/.cache/page-ssr/routes/render-page.js:54344:1
  
  - render-page.js:100310 __webpack_require__
    /Users/me/dev/gatsby-frontend/.cache/page-ssr/routes/render-page.js:100310:42
  
  - render-page.js:53562 Module.2736
    /Users/me/dev/gatsby-frontend/.cache/page-ssr/routes/render-page.js:53562:12
  
  - render-page.js:100310 __webpack_require__
    /Users/me/dev/gatsby-frontend/.cache/page-ssr/routes/render-page.js:100310:42
  
  - render-page.js:52927 Module.9874
    /Users/me/dev/gatsby-frontend/.cache/page-ssr/routes/render-page.js:52927:1599
  
  - render-page.js:100310 __webpack_require__
    /Users/me/dev/gatsby-frontend/.cache/page-ssr/routes/render-page.js:100310:42
  
  - render-page.js:53474 Module.3451
    /Users/me/dev/gatsby-frontend/.cache/page-ssr/routes/render-page.js:53474:495
  
  - render-page.js:100310 __webpack_require__
    /Users/me/dev/gatsby-frontend/.cache/page-ssr/routes/render-page.js:100310:42
  
  - render-page.js:100454 
    /Users/me/dev/gatsby-frontend/.cache/page-ssr/routes/render-page.js:100454:37
  
  - render-page.js:100459 Object.<anonymous>
    /Users/me/dev/gatsby-frontend/.cache/page-ssr/routes/render-page.js:100459:12
  
  - v8-compile-cache.js:192 Module._compile
    [gatsby-frontend]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - index.ts:1056 Module.m._compile
    [gatsby-frontend]/[ts-node]/src/index.ts:1056:23
  
  - loader.js:1114 Module._extensions..js
    internal/modules/cjs/loader.js:1114:10
  
  - index.ts:1059 Object.require.extensions.<computed> [as .js]
    [gatsby-frontend]/[ts-node]/src/index.ts:1059:12
```

**Comment by angeloashmore** [comment]
Hi @justinluttrell, thanks for all the details.

I see a reference to `ts-node` in the second error. Does your project have anything unique to your setup? Such as writing `gatsby-node.ts` in TypeScript?

I haven't come across this error before so I'm wondering how it can be reproduced to find a fix. Thanks!

**Comment by justinluttrell** [comment]
Yes you're right. We use `ts-node` so that we can write `gatsby-node.ts` in TypeScript. I'm not sure of anything else unique that may impact the use of these plugins though.

**Comment by angeloashmore** [comment]
Hi @justinluttrell, sorry for such a late reply. The error seems related to `ts-node` and potentially another process reading source maps. Does this still happen if you don't use `ts-node`? (As a quick test, you could compile your `gatsby-node.ts` file to `.js` and run Gatsby's development process.)

Gatsby v4.9 now includes native support for `gatsby-node.ts` (and all other `gatsby-*.ts` files), so you could remove `ts-node` from your project if you're able to upgrade.

**Comment by justinluttrell** [comment]
Hey Angelo, we recently upgraded to Gatsby v4.9 and this solved the issue. 

Thanks for your response!

**Comment by angeloashmore** [comment]
That's great to hear! Thanks for the follow-up. The new native TypeScript support is such a nice thing to have built-in.
