### ISSUE TITLE
Images that have special characters in their file name do not preview correctly

### ISSUE THREAD

**Issue by schweetheart** [prismicio/prismic-gatsby#486]
### Versions
- gatsby": "^3.8.1",
- gatsby-source-prismic: "^4.0.1",
- gatsby-plugin-prismic-previews: "^4.0.1",
- node: 16.13.0

### Reproduction

When attempting to preview certain images which file name contains special characters, the preview of that image fails.

1) Upload a file with special characters in its name (The + sign)
**Filename**
`LM+_HS Creative_Gifting_homepage-banner-compoundpath-01.svg
`
2) The link to the image in the prismic writing room works
[https://lmplus.cdn.prismic.io/lmplus/751c59c8-7a14-41d4-95eb-0d4cc22d2e16_LM+_HS%20Creative_Gifting_homepage-banner-compoundpath-01.svg](https://lmplus.cdn.prismic.io/lmplus/751c59c8-7a14-41d4-95eb-0d4cc22d2e16_LM+_HS%20Creative_Gifting_homepage-banner-compoundpath-01.svg)

3) When trying to preview that image as part of a document - the prismic preview plugin resolves the image to the following (broken) URL
[https://lmplus.cdn.prismic.io/lmplus/751c59c8-7a14-41d4-95eb-0d4cc22d2e16_LM%2B_HS+Creative_Gifting_homepage-banner-compoundpath-01.svg
](https://lmplus.cdn.prismic.io/lmplus/751c59c8-7a14-41d4-95eb-0d4cc22d2e16_LM%2B_HS+Creative_Gifting_homepage-banner-compoundpath-01.svg
)

**Comment by angeloashmore** [comment]
Hi @schweetheart, apologies on the late reply. I had some time off at the end of the year and am getting back to work now. :)

This issue will be addressed in a future release. Imgix (Prismic's image host) has strict URL requirements that make working with special characters (spaces, pluses, etc.) difficult. The solution is not immediately obvious so I'll need some time to come up with a fix.

In the mean time, this can be fixed temporarily by renaming and reuploading the file without pluses in the filename. Thanks!

**Comment by angeloashmore** [comment]
This issue is stale and may be fixed in a recent version. Please update to the latest version and try again. If the issue continues to be a problem, please open a new issue. Thank you!

See the documentation for guides on updating to the latest versions: [Gatsby + Prismic Migration Guides](https://github.com/prismicio/prismic-gatsby/tree/main/docs#migration-guides)
