### ISSUE TITLE
Removed legacy field from Custom Type, now previews in development are not working

### ISSUE THREAD

**Issue by kb1995** [prismicio/prismic-gatsby#496]
### Versions

- gatsby-source-prismic: ^5.2.5
- gatsby-plugin-prismic-previews: ^5.2.5
- node: v14.17.6

### Reproduction

- gatsby-config.js

```js
module.exports.plugins.push({
  resolve: 'gatsby-source-prismic',
  options: {
    repositoryName: GATSBY_PRISMIC_REPO_NAME,
    linkResolver: doc => linkResolver(doc),
    customTypesApiToken: PRISMIC_CUSTOM_TYPES_API_TOKEN,
  },
});
```

- gatsby-ssr.js

```js
export const wrapRootElement = ({ element }) => (
  <PrismicPreviewProvider repositoryConfigs={repositoryConfigs}>{element}</PrismicPreviewProvider>
);
```

- repository config

```js
import linkResolver from '@prismic/utils/linkResolver';
import { componentResolverFromMap } from 'gatsby-plugin-prismic-previews';

import HowToBuildPageTemplate from '@templates/howToBuild-template';
import HowToDevelopPageTemplate from '@templates/howToDevelop-template';
import CustomerPageTemplate from '@templates/customer-template';
import BlogPost from '@templates/blogPost';
import AcademyPost from '@templates/academyPost';
import LandingPage from '@templates/landing';
import AcademyLanding from '@templates/academyLanding';
import Author from '@templates/author';
import Category from '@templates/category';

export const repositoryConfigs = [
  {
    repositoryName: process.env.GATSBY_PRISMIC_REPO_NAME,
    linkResolver,
    componentResolver: componentResolverFromMap({
      how_to_build_page: HowToBuildPageTemplate,
      how_to_develop_page: HowToDevelopPageTemplate,
      customer_page: CustomerPageTemplate,
      blog_post: BlogPost,
      academy_post: AcademyPost,
      landing_page: LandingPage,
      academy_landing: AcademyLanding,
      person: Author,
      category: Category,
    }),
  },
];
```

### Steps to reproduce

1. I had a legacy author field in my blog post (replaced with a group field), which I removed
2. I removed it (the custom type is still existing)
3. When I try to preview any document (even if not blog) I get the following error

```
No type for path: blog_post.data.author. Did you register the Custom Type model?
```

4. I did clean the cache but it didn't help

5. I re-added the old field and now previews are working once again

### What is expected?

Previews to work

### What is actually happening?

I get the error above. It seems to be working in production however

**Comment by angeloashmore** [comment]
Hey @kb1995, this is probably happening because some `blog_post` documents still contain an `author` field, even after removing the field from the Custom Type. In Prismic, the field won't be removed from the API response until you go into a document and save a new version.

During a preview, the plugin iterates through each field and looks at the Custom Type models to find a field type. Since it comes across an `author` field, but cannot find a matching field in the Custom Type, it doesn't know how to handle it.

If this is the issue, you can fix this by going into each document, editing a field (such as deleting a character from a field and adding it back in), and publishing a new version. This keeps your content unchanged, but saves a new version.

Unfortunately, you will need to go through each Blog Post document to fix this.

Please let me know if you have any questions about this. Thanks!

**Comment by kb1995** [comment]
@angeloashmore Thanks for the reply!

I just went through every single blog post document to double check and I can confirm that none of them had the legacy author field filled in (I migrated all of them couple of weeks ago when I made this field a legacy one). So maybe it's something else?

Even if this wasn't the case, is there nothing from a technical standpoint we could about that? I currently only have <10 blog posts for this client, but you can understand the problem if there were >500 documents (I do have clients with that many blog posts)

**Comment by angeloashmore** [comment]
Hey @kb1995, so sorry for the late reply! This slipped through my notifications.

Even if the documents did not have a value for the legacy `author` field, it might still be included in the API response. You can check for this using Prismic's API browser (https://your-repo-name.prismic.io/api/v2 or https://qwerty.prismic.io/graphql if you find GraphQL to be easier). The fact that it's a content relationship field shouldn't matter here.

Did you confirm that all Blog Post documents are no longer returning those fields? Again, you would need to re-publish those documents for the field to be removed. (This is a technical limitation of the API, unfortunately)

> Even if this wasn't the case, is there nothing from a technical standpoint we could do about that? I currently only have <10 blog posts for this client, but you can understand the problem if there were >500 documents (I do have clients with that many blog posts)

I totally understand how this is a deeper problem where re-publishing documents manually is not a viable solution. In those cases, there are other workarounds, such:
- Keep the legacy field, but move it to another tab in the Custom Type so it's hidden away from the primary view.
- Remove the legacy field, but add it back to the Custom Type JSON in Gatsby. You can continue using `customTypesApiToken`, but you would need to manually provide the JSON for Blog Post with that field added (can be done with merging)

If you run into this problem, I can help figure out a solution that, hopefully, is easy to maintain. I 100% recognize that these are workarounds to a limitation in the Prismic API.

**Comment by kb1995** [comment]
@angeloashmore Thanks for the response! Closing since it's a technical limitation of Gatsby/Prismic API

**Comment by kilinkis** [comment]
also have been fighting with this. Extremely annoying issue.
