### ISSUE TITLE
dangerouslyGetAll breaks all prismic queries

### ISSUE THREAD

**Issue by kb1995** [prismicio/prismic-gatsby#497]
### Versions

- gatsby-source-prismic: 5.2.5
- gatsby-plugin-prismic-previews: 5.2.5
- node: v14.17.6

### Steps to reproduce

1. Upgrade to "gatsby-plugin-prismic-previews": "^5.2.5" and "gatsby-source-prismic": "^5.2.5"
2. `gatsby clean` just in case
3. `yarn run dev`

Nothing is loaded when not in preview (I have ~100 Content Post live documents):

<img width="779" alt="Screenshot 2022-02-10 at 11 28 18" src="https://user-images.githubusercontent.com/32920882/153399888-fe6b0a94-ade8-49c3-854c-50547ccc88b3.png">

When I try to preview a document, I get a more helpful error message

<img width="1313" alt="Screenshot 2022-02-10 at 11 28 34" src="https://user-images.githubusercontent.com/32920882/153400152-d81586aa-165d-4b0b-97e7-2f31347c9ec4.png">

I had to upgrade the prismic gatsby due to another preview bug, which I'll document in another issue. I'll downgrade to an earlier version (5.2.0) in the meantime

### What is expected?

Prismic content to be queried and loaded correctly.

### What is actually happening?

No Prismic content is being loaded.

**Comment by angeloashmore** [comment]
Hey @kb1995, apologies for the late reply. The version of `@prismicio/client` has been updated to the latest current version, `v6.4.2`, which will ensure the correct version is used.

This update to the Gatsby plugins will be published soon with this fix.
