### ISSUE TITLE
Question about imageImgixParams (&q=50)

### ISSUE THREAD

**Issue by jodiedoubleday** [prismicio/prismic-gatsby#498]
Apologies if this is not a plugin issue but a general Prismic issue...

I noticed a strange issue with one of our image-heavy clients.

By default images are returned from imgix with the following params
```
?ixlib=gatsbyFP&q=50&auto=compress%2Cformat&w={imgwidth}&h={imgheight}
```

I've been looking at reducing the file size of the images and decided to play around with the q (quality) parameter which by default is set to 50 (as above)
If in my config I set q to be blank...
```
imageImgixParams: {
  q: ''
}
```
This actually results in a smaller file size, which is found odd.
Upon further reading - https://docs.imgix.com/apis/rendering/format/q it states...
**_When [auto=compress](https://docs.imgix.com/apis/rendering/auto/auto) is applied to an image, the default value becomes 45 unless overridden._**

So either this plugin or Prismic is overwriting imgix's default image quality compression and naturally making the file size bigger.

Should the q parameter be removed by default?

### Versions

- gatsby-source-prismic: 5.0.3
- gatsby-plugin-prismic-previews: 5.0.3
- node: 14.17.3

### Reproduction
_coming soon_

### Steps to reproduce
run any site using the standard out the box Imgix setup. Check the file size (kb) of an image, then add a blank q parameter to config and check the file size, it should result in a smaller image.

### What is expected?
I think the q parameter should be removed by default and instead reply on Imgix compression. If you want to override that q value you should have to add it to the config.

### What is actually happening?
The image file sizes are purposely made larger by default.

**Comment by angeloashmore** [comment]
Hey @jodiedoubleday, you're absolutely right. `q=50` will be removed in the version which should be published soon. Until then, the parameter can be disabled using `{ q: undefined }` or `{ q: '' }` like you pointed out.

Thanks for finding this!
