### ISSUE TITLE
Fragments on a non-slice queries

### ISSUE THREAD

**Issue by kb1995** [prismicio/prismic-gatsby#501]
I'm not sure if it's currently possible to do that and it's just a limitation of my knowledge in GraphQL, but I can't figure out how to create Fragments for non-slice queries.

I'm already using Fragments for slice components as documented in the docs, but I'd like to also use fragments for my article cards which I query multiple times across multiple pages, which means that I end up repeating myself.

This is what I've tried:

```
import { graphql } from 'gatsby';

export const query = graphql`
  fragment AcademyCard on PrismicAcademyPost {
    author {
      document {
        ... on PrismicPerson {
          id
          data {
            name
          }
        }
      }
    }
    authors {
      author_doc {
        document {
          ... on PrismicPerson {
            data {
              name
            }
          }
        }
      }
    }
  }
`;
```

then 

```
    allPrismicAcademyPost(
      sort: { fields: data___published_date, order: DESC }
      filter: { data: { categories: { elemMatch: { category: { uid: { eq: $uid } } } } } }
    ) {
      nodes {
        id
        url
        data {
          ...AcademyCard
          published_date

...
```

However, I'm getting the following error message

```
There was an error in your GraphQL query:

Cannot query field "author" on type "PrismicAcademyPost".
```

I've tried several variations of this, but nothing seems to work.

Any help is appreciated!

**Comment by angeloashmore** [comment]
Hey @kb1995, what you are doing is correct, except that the type name is incorrect.

```graphql
fragment AcademyCard on PrismicAcademyPost {
  # ...fields...
}
```

The `on PrismicAcademyPost` part of that fragment means it can be used on `PrismicAcademyPost` nodes. This is the object that contains fields like `id`, `uid`, `last_published_on`, and `data`. It does not contain your content fields; those are in `data`.

Instead, you can update your fragment to the following:

```graphql
fragment AcademyCard on PrismicAcademyPostDataType {
  # ...fields...
}
```

Note that `PrismicAcademyPost` is now `PrismicAcademyPostDataType`. This is the type that contains your document's content fields. You can confirm this by opening GraphiQL (<http://localhost:8000/___graphql> when your dev server is running) and looking at the type of `PrismicAcademy`'s `data` field.

You can now use the fragment in a GraphQL query like this:

```graphql
query {
  allPrismicAcademyPost(
    sort: { fields: data___published_date, order: DESC }
    filter: {
      data: { categories: { elemMatch: { category: { uid: { eq: $uid } } } } }
    }
  ) {
    nodes {
      id
      url
      data {
        ...AcademyCard
        published_date
      }
    }
  }
}
```

Hope that helps! If that didn't work, let me know and I'll try to figure out what went wrong. Thanks!
