### ISSUE TITLE
Don't load Google Font

### ISSUE THREAD

**Issue by EpokK** [prismicio/prismic-gatsby#509]
https://github.com/prismicio/prismic-gatsby/blob/4d7e9e3c402ee30233963bfeb833164d038a1bfc/packages/gatsby-plugin-prismic-previews/src/styles.css#L1

For privacy reasons, it could be nice to not upload Google Font here.

**Comment by angeloashmore** [comment]
The latest version of `gatsby-plugin-prismic-previews` no longer loads Google Fonts.

See the documentation for guides on updating to the latest versions: [Gatsby + Prismic Migration Guides](https://github.com/prismicio/prismic-gatsby/tree/main/docs#migration-guides)
