### ISSUE TITLE
Preview not redirecting to correct page 

### ISSUE THREAD

**Issue by greatwitenorth** [prismicio/prismic-gatsby#517]
### Versions

- gatsby-source-prismic: 5.2.9
- gatsby-plugin-prismic-previews: 5.2.8
- node: v16.15.0

### Reproduction

I can provide access to a private bitbucket repo if needed.

I cannot seem to get previews working with our repository. When I click a preview for my local instance (while using gatsby develop) I just see my preview page, and it never redirects to the correct page. There's also no javascript errors:

<img width="1723" alt="Screen Shot 2022-08-10 at 3 24 07 PM" src="https://user-images.githubusercontent.com/547583/184013057-24a35cb5-1cbf-4db7-858b-495802f5b168.png">

When I try viewing on production I see the error `t is not a function` and no relevant errors in the console:

<img width="1721" alt="Screen Shot 2022-08-10 at 3 24 57 PM" src="https://user-images.githubusercontent.com/547583/184013274-bc65d803-9f56-4f6c-92af-342d3c919031.png">

<details open>
<summary>Additional Details</summary>
<br>

**preview.js**

```
import * as React from "react"
import { withPrismicPreviewResolver } from "gatsby-plugin-prismic-previews"
import Layout from "../layout"
import Container from "../components/atoms/Container"

const PreviewPage = () =>
  (
    <Layout>
      <Container>
        <p>Loading preview...</p>
      </Container>
    </Layout>
  )

export default withPrismicPreviewResolver(PreviewPage)

```

**gatsby-browser.js**

```
import * as React from 'react'
import { componentResolverFromMap, PrismicPreviewProvider } from "gatsby-plugin-prismic-previews"
import linkResolver from "./src/utils/link-resolver"
import Page from "./src/templates/page"
import Insight from "./src/templates/insight"
import CaseStudy from "./src/templates/case_study"

export const wrapRootElement = ({ element }) => (
  <PrismicPreviewProvider
    repositoryConfigs={[{
      repositoryName: "weareroadmap",
      linkResolver,
      componentResolver: componentResolverFromMap({
        page: Page,
        insight: Insight,
        case_study: CaseStudy
      }),
    }]}
  >{element}</PrismicPreviewProvider>
)
```

**link-resolver.js**

```
const pluralize = require('pluralize/pluralize')

const linkResolver = (doc) => {
  // Your link resolver
  if (doc.uid === "home") {
    return "/"
  }

  let type = ""
  if (typeof doc.type !== "undefined" && doc.type !== "page") {
    let typeParts = doc.type.split("_")
    typeParts[typeParts.length - 1] = pluralize(typeParts[typeParts.length - 1])
    type = "/" + typeParts.join("-")
  }

  const prefix = typeof doc.data !== "undefined" && doc.data.slug_prefix ? doc.data.slug_prefix + "/" : ""

  return type + "/" + prefix + doc.uid + "/"
}

exports.linkResolver = linkResolver;
```

</details>

### Steps to reproduce

- Visit document in prismic editor
- click preview -> local

### What is expected?

- to see the updated content in the preview

### What is actually happening?

- I'm only seeing the contents of my `preview.js` page

**Comment by angeloashmore** [comment]
Glad to hear you found the issue, @greatwitenorth. Sorry I didn't get a chance to reply to you earlier!

Perhaps there's a way we can make the issue more obvious, such as providing clearer error messages or simplifying the set up process. We can explore this in the next major version (#514).
