### ISSUE TITLE
Cannot read properties of null (reading 'link_type')

### ISSUE THREAD

**Issue by kieranstartup** [prismicio/prismic-gatsby#527]
### Versions

- gatsby-source-prismic:  5.2.10
- gatsby-plugin-prismic-previews:  5.2.10
- node:  v18.14.0
- @prismicio/react: 2.5.2

### Reproduction
1. I can try and set up a reproduction / invite you to the repository if useful, but I'm hoping it's some kind of a simple fix. Possibly related to: https://github.com/prismicio/prismic-gatsby/issues/312#issue-797807070

### Error Message
```
error "gatsby-source-prismic" threw an error while running the sourceNodes lifecycle:

Cannot read properties of null (reading 'link_type')

TypeError: Cannot read properties of null (reading 'link_type')
  
- normalizeDocumentSubtree.ts:436 
[project_name]/[gatsby-source-prismic]/src/lib/normalizeDocumentSubtree.ts:436:27
  
- Chain.js:9 
[project_name]/[fp-ts]/lib/Chain.js:9:103
  
- EitherT.js:77 
[project_name]/[fp-ts]/lib/EitherT.js:77:116
  
- ReaderT.js:18 
[project_name]/[fp-ts]/lib/ReaderT.js:18:116
  
- Task.js:136 
[project_name]/[fp-ts]/lib/Task.js:136:37
  
- task_queues:95 processTicksAndRejections
node:internal/process/task_queues:95:5
  
  - async Promise.all
  
  - async Promise.all
  
  - source-nodes.ts:50 Object.sourceNodes
    [project_name]/[gatsby-source-prismic]/src/source-nodes.ts:50:9
  
  - api-runner-node.js:487 runAPI
    [project_name]/[gatsby]/src/utils/api-runner-node.js:487:16
```

### Steps to reproduce
1. Create slice which includes integration field to Shopify catalog
2. Add product to integration field
3. Change field from integration field to content relationship
4. Add page/document into field
5. Run ```gatsby develop```
6. Encounter error

### What is expected?
1. No error?

### What is actually happening?
1. Site is failing to run both locally and in production
2. Site returns null

Thanks!

**Comment by kieranstartup** [comment]
Looking into this a bit further I think the issue is potentially related to broken links inside the new content relationship field.

I tried deleting the new content relationship field I added in, and then querying the page through the Prismic API Browser and the API still returns the deleted fields. Here's a screenshot showing you an example:

![Screenshot 2023-02-28 at 16 29 21](https://user-images.githubusercontent.com/5398966/221916562-6a4e418e-e22b-4af5-bcec-9368536fe6ca.jpg)

So I'm not sure if this is an issue with the plugin, or a bigger issue with the API itself?

When I re-created the content relationship field and went back to the document in Prismic it shows the 'Broken link' message. So I'm not sure if it's related to this either: https://github.com/prismicio/prismic-gatsby/issues/28#issue-321299394

Thanks!

**Comment by kieranstartup** [comment]
I've managed to get my site running with ```gatsby develop``` again after archiving and individually re-publishing every document in my Prismic repository to figure out where the issue was occurring.

As I suspected in my follow up comment above, it was caused by broken links inside a Content Relationship field. 

I've ran into similar issues before but the error has always been on the frontend, it's never stopped me from managing to get the site running locally.

Let me know if there's any information I can supply to help you get to the bottom of the issue.

Thanks!

**Comment by angeloashmore** [comment]
This issue may be fixed in a recent version. Please update to the latest version and try again. If the issue continues to be a problem, please open a new issue. Thank you!

See the documentation for guides on updating to the latest versions: [Gatsby + Prismic Migration Guides](https://github.com/prismicio/prismic-gatsby/tree/main/docs#migration-guides)
