### ISSUE TITLE
Error: Value is not expected type Image

### ISSUE THREAD

**Issue by ostaoleho** [prismicio/prismic-gatsby#528]
### Versions

- gatsby-source-prismic: ^5.2.10
- gatsby-plugin-prismic-previews: ^5.2.10
- gatsby: ^4.20.0
- node: 16.18.1

### Steps to reproduce

Update Gatsby to v4 and Prismic to v5 an image with empty data returns null and throws an error.

### What is expected?
Preview loads without image error.

### What is actually happening?
I have the page templates builded with Prismic. One of content is image that is not required. I made upgrade from gatsby from v3 to v4 and Prismic from v3 to v5 build and site works correct. But when I try visit site with preview mode i have an error **Value is not expected type Image**.

#### In Prismic Image field is default
<img width="1064" alt="Screenshot 2023-03-01 at 13 02 30" src="https://user-images.githubusercontent.com/78026498/222123135-7e011bf7-4414-45e0-b92d-c25268817270.png">

#### In preview data structure come like this. Thumbnail is object but image is null.
<img width="535" alt="Screenshot 2023-02-28 at 23 03 11" src="https://user-images.githubusercontent.com/78026498/222124095-9dbc3fa8-465d-4b77-8335-1c4d1fa76b9e.png">

#### In schema I have this code
<img width="281" alt="Screenshot 2023-03-01 at 13 29 07" src="https://user-images.githubusercontent.com/78026498/222127011-20a1174f-c984-4019-a0a9-41f196069f7d.png">

**Comment by jorge-braz** [comment]
I have the same error.

**Comment by angeloashmore** [comment]
This issue may be fixed in a recent version. Please update to the latest version and try again. If the issue continues to be a problem, please open a new issue. Thank you!

See the documentation for guides on updating to the latest versions: [Gatsby + Prismic Migration Guides](https://github.com/prismicio/prismic-gatsby/tree/main/docs#migration-guides)
