### ISSUE TITLE
createSchemaCustomization lifecycle failing with Gatsby 5.10.0

### ISSUE THREAD

**Issue by mudge** [prismicio/prismic-gatsby#531]
### Versions

- gatsby-source-prismic: v5.3.0
- gatsby-plugin-image: v3.10.0
- @imgix/gatsby: v1.7.5
- gatsby: v5.10.0
- node: v18.15.0

### Reproduction

See https://github.com/ghostcassette/gatsby-prismic-graphql-types for a reproducible test case. You'll need to provide the required environment variables for the `gatsby-config.js` but then running `yarn build` should trigger the error.

<details open>
<summary>Additional Details</summary>
<br>
The output of `yarn build`:

```
$ gatsby build
success compile gatsby files - 0.196s
success load gatsby config - 0.014s
success load plugins - 1.216s
success onPreInit - 0.000s
success initialize cache - 0.040s
success copy gatsby files - 0.061s
success Compiling Gatsby Functions - 0.097s
success onPreBootstrap - 0.105s

 ERROR #11321  API.NODE.EXECUTION

"gatsby-source-prismic" threw an error while running the createSchemaCustomization lifecycle:

Cannot read properties of undefined (reading 'slice')



  TypeError: Cannot read properties of undefined (reading 'slice')
  
  - graphqlTypes.ts:57 
    [gatsby-prismic-graphql-types]/[@imgix]/gatsby/src/modules/gatsby-plugin/graphqlTypes.ts:57:35
  
  - Array.reduce
  
  - graphqlTypes.ts:24 ImgixParamsInputType
    [gatsby-prismic-graphql-types]/[@imgix]/gatsby/src/modules/gatsby-plugin/graphqlTypes.ts:24:54
  
  - typeBuilder.ts:55 buildImgixGatsbyTypes
    [gatsby-prismic-graphql-types]/[@imgix]/gatsby/src/modules/gatsby-plugin/typeBuilder.ts:55:47
  
  - pluginHelpers.ts:16 Object.createImgixGatsbyTypes
    [gatsby-prismic-graphql-types]/[@imgix]/gatsby/src/pluginHelpers.ts:16:24
  
  - buildImageBaseFieldConfigMap.ts:121 
    [gatsby-prismic-graphql-types]/[gatsby-source-prismic]/src/builders/buildImageBaseFieldConfigMap.ts:121:16
  
  - Chain.js:15 
    [gatsby-prismic-graphql-types]/[fp-ts]/lib/Chain.js:15:103
  
  - EitherT.js:83 
    [gatsby-prismic-graphql-types]/[fp-ts]/lib/EitherT.js:83:97
  
  - ReaderT.js:24 
    [gatsby-prismic-graphql-types]/[fp-ts]/lib/ReaderT.js:24:97
  
  - Task.js:133 
    [gatsby-prismic-graphql-types]/[fp-ts]/lib/Task.js:133:41
  
  - task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5
  
  - async Promise.all
  
  - create-schema-customization.ts:155 Object.createSchemaCustomization
    [gatsby-prismic-graphql-types]/[gatsby-source-prismic]/src/create-schema-customization.ts:155:9
  
  - api-runner-node.js:509 runAPI
    [gatsby-prismic-graphql-types]/[gatsby]/src/utils/api-runner-node.js:509:16
  

not finished createSchemaCustomization - 0.848s

error Command failed with exit code 1.
```
</details>

### Steps to reproduce

1. Configure gatsby-source-prismic 5.3.0 with Gatsby 5.10.0
2. Attempt to run a full Gatsby build with `yarn build`

### What is expected?

The build should succeed.

### What is actually happening?

The build errors out with:

```
"gatsby-source-prismic" threw an error while running the createSchemaCustomization lifecycle:

Cannot read properties of undefined (reading 'slice')
```

(See "Additional Details" above for the full output.)

**Comment by ochoarobert1** [comment]
We have made a test locking one dependency of gatsby-source-prismic 

imgix-url-params to "11.13.1" and it's running now.

I don't know why this newer version is breaking the build. 
Hope with this you are able to build the project again.

**Comment by mudge** [comment]
Thanks @ochoarobert1, I can confirm adding the following [selective dependency resolution](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to our `package.json` means we can successfully run a build now:

```json
  "resolutions": {
    "imgix-url-params": "11.13.1"
  },
```

Looking at [the diff between imgix-url-params 11.13.1 and 11.15.0](https://github.com/imgix/imgix-url-params/compare/11.13.1...11.15.0), could there be some issue where an inconsistent version of [`parameters.json`](https://github.com/imgix/imgix-url-params/blob/master/dist/parameters.json) is being used resulting in one package trying to check a deprecated param against a newer version?

**Comment by ochoarobert1** [comment]
I guess that exactly is the problem. I cannot confirm which deprecated parameter is being used in this version of the repo. (There's no warning at all)

I figure it out this error because I'm making a controlled upgrade from Gatsby 4 to 5 and this error popups out a few days ago.

I'm glad that you are able to build the project again.

**Comment by angeloashmore** [comment]
Hi @mudge and @ochoarobert1,

Thank you for sharing these details and a workaround! Could you try this alpha version of the plugin and let me know if it fixes the issue?

I updated `@imgix/gatsby` in both plugins which seems to resolve the error on my end. (See PR #532)

```sh
npm install gatsby-source-prismic@5.3.1-alpha.0 gatsby-plugin-prismic-previews@5.3.1-alpha.0
```

Thank you!

**Comment by zinodaks** [comment]
So glad that I stumbled upon this. It was driving me crazy & I couldn't find out what the problem was since the code was working fine before

**Comment by ochoarobert1** [comment]
@angeloashmore I'm able to build with these two dependencies you sent. 
For installation I had to use --legacy-peer-deps because the prismic previews@5.3.1-alpha0 is looking for source-prismic@5.3.0 

I've tested the build and I'm able to complete it with the latest version of imgix/gatsby.

**Comment by angeloashmore** [comment]
Perfect, thank you @ochoarobert1! I updated the command above to include `--legacy-peer-deps` for anyone else coming to this thread later.

I will be merging and publishing the alpha version as latest.

**Comment by angeloashmore** [comment]
This issue should be fixed as of `v5.3.1`. Thank you everyone for your help diagnosing the error! 🙂

You can update to the latest version with the following commands:

```
npm install gatsby-source-prismic@latest
npm install gatsby-plugin-prismic-previews@latest
```

If this doesn't resolve the issue, please comment here and I will take another look.

**Comment by mudge** [comment]
Thanks for the new release, @angeloashmore. I confirm it fixes the problem for us too.

**Comment by angeloashmore** [comment]
Thank you for confirming, @mudge!
