### ISSUE TITLE
Update react-shadow to get rid of peerDep warnings

### ISSUE THREAD

**Issue by jsvegborn** [prismicio/prismic-gatsby#533]
Hi! 

It would be great if **react-shadow** for **gatsby-plugin-prismic-previews** could be updated to v20, since the current version seem to cause a lot of peerDep conflict warnings after upgrading to Gatsby v5.

Thanks for you work! 😊

<img width="679" alt="Screenshot 2023-06-05 at 12 33 55" src="https://github.com/prismicio/prismic-gatsby/assets/26543619/093ddb86-bdef-4bcb-974d-020463f871ab">

**Comment by angeloashmore** [comment]
The latest version of `gatsby-plugin-prismic-preview` no longer uses `react-shadow`, so this issue should be resolved. Thank you for reporting!
