### ISSUE TITLE
[V6] Inconsistent gatsbyImageData responses after upgrade

### ISSUE THREAD

**Issue by finematterdave** [prismicio/prismic-gatsby#537]
### Versions

- `gatsby-source-prismic`: 6.0.0
- `gatsby`: 5.11.0
- Node.js: v18.12.1

### Reproduction

After upgrading the gatsby prismic plugin to v6, we're seeing some images fail to be pulled through via graphql queries (causing graphql errors in the build process). Confirmed this seems to be due to some images that used to work that now don't, so might be an underlying change in how Prismic returns some types of images, or the error handling? It's happening on a number of different pages with a number of different images, but haven't seen any commonality in the images yet.

Bad image example (which was returned correctly in V5): "https://images.prismic.io/finematter-development/e9e0fae7-c346-4cb5-8a1c-32c2c04b3501_https___images.finematter.com_elhanati_4b070341-5315-4acc-8bb1-d402f910719d_model_women_FINEMATTER+SS22_2082+%28FM+size%29.avif?auto=compress,format"

Good (works in V5 or V6): https://images.prismic.io/finematter-development/45955ade-0c9e-449e-8e7c-aa8942ba65da_R0031249.jpg?auto=compress,format

Error returned when a "bad" image is present:

```
Unexpected token  in JSON at position 0

  579 |               richText
  580 |             }
  581 |             item_title
  582 |           }
  583 |         }
  584 |         ... on PrismicPageDataBodyTwoColumnsWithImage {
  585 |           __typename
  586 |           slice_type
  587 |           primary {
  588 |             image1 {
> 589 |               gatsbyImageData(width: 800, breakpoints: [400])
      |               ^
  590 |             }
  591 |             quote {
  592 |               richText
  593 |               html
  594 |             }
  595 |             twi_title: title1 {
  596 |               richText
  597 |             }
  598 |             author_image {
  599 |               gatsbyImageData(width: 200, breakpoints: [400])
```

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Add one of the above images to a document, and `gatsby build`

### What is expected?
Both images are returned in either scenario

### What is actually happening?
Graphql error shown above for the "bad" image example

**Comment by dturkington49** [comment]
We've also encountered this issue and is blocking our upgrade to Gatsby 5.

**Comment by dturkington49** [comment]
Here's a couple of example images which were "bad" and causing the above error.

https://images.prismic.io/xometry-marketing/3ec2fc83-db31-4ccd-a6d5-7e02d79879a5_icon-industries-robotics-factory-001-20180305-adobestockID-127665662.png?auto=compress,format
https://images.prismic.io/xometry-marketing/d48da758-fb01-42a7-8b23-62a279ae395e_icon-industries-logistics-speed-001-20180305-adobestockID-127663570.png?auto=compress,format

I was able to work out this problem by navigating to the corresponding document in Prismic, re-selecting the image from the image library for all broken fields and publishing the document. I did not crop the images after re-selection so I'm unsure if that is related the breakage.

**Comment by calluna18** [comment]
Thanks @dturkington49! We also solved it by finding the "bad" image in Prismic. I our case, changing it from avif to jpeg seemed to do the trick :)

**Comment by angeloashmore** [comment]
It seems Imgix has broken/limited support for AVIF source images. I came across an issue yesterday where parameters like `rect` don't work on AVIF images, but do on an equivalent PNG or JPEG.

The Gatsby plugin uses `palette=json` to gather color metadata about the image, which is necessary for placeholders. AVIF images ignore these parameters and always return the binary image.

So for now, avoid using AVIF source images. You can continue serving AVIF images via `auto=format` or `fm=avif`—just don't upload AVIF images to Prismic.

**Comment by finematterdave** [comment]
@angeloashmore thanks, makes sense! We'll change our internal processes to limit this (and do some whack-a-mole to remove the existing AVIF images). Worth raising on the Imgix GH? It's a very non-obvious error, so if you want to point me at the area I can add some error handling too via a PR.
