### ISSUE TITLE
Can't access data inside link fields when in a preview session

### ISSUE THREAD

**Issue by kieranstartup** [prismicio/prismic-gatsby#541]
Hey, 

So this may be related to issue #422, but whenever I'm previewing a document and trying to access a link field, the field returns Proxy(Object), rather than the url. This is probably fine in a lot of cases, but in my case I'm trying to access a Vimeo mp4 file link, and then preview that within a ```<video>```, so it's causing some issues where my client can't preview their changes.

### Versions

- `gatsby-source-prismic`: 6.0.0
- `gatsby-plugin-prismic-previews`: 6.0.0
- `gatsby`: 5.11.0
- `Node.js`: v18.14.0

### Steps to reproduce
Add a link field to a slice. Add a link (in my case a link to a Vimeo mp4 video file).

### What is expected?
Link field outputs the url, and displays the video.

### What is actually happening?
Link field outputs Proxy(Object) instead of a url. I've tried following some of the suggestions in issue 422 with optional chaining but it's not getting me anywhere.

### Screenshots
![Screenshot 2023-08-10 at 17 57 14](https://github.com/prismicio/prismic-gatsby/assets/5398966/8e3d81eb-6490-48a8-9539-8f4a6d7f8ec2)

![Screenshot 2023-08-10 at 17 56 21](https://github.com/prismicio/prismic-gatsby/assets/5398966/b1f81061-591e-44d8-87fa-17ea2cb490d1)

Let me know if you have any thoughts or need anything else to help replicate.

Thanks!

**Comment by jodiedoubleday** [comment]
is there any update/ fix for this issue @angeloashmore?

**Comment by kieranstartup** [comment]
@jodiedoubleday I don't think we'll be getting much support on the plugin going forward based on this [blogpost](https://prismic.io/blog/gatsby-prismic-v6). And it looks like Netlify laid off most of the Gatsby team too 😬

**Comment by kb1995** [comment]
@jodiedoubleday @kieranstartup - would you recommend upgrading to v6? 

My client and I have been waiting for v6 for half a year, but I'm a bit anxious upgrading it due to bugs like this and the lack of support from Prismic/Gatsby teams.

**Comment by jodiedoubleday** [comment]
@kb1995 I think in all honesty it's still better to upgrade.
There are a few small bugs that need fixing but nothing serious, it's soo much faster to preview large repos.

**Comment by kieranstartup** [comment]
@kb1995 Yeah I second that, it's definitely still better to upgrade. As a heads up, the docs are all [here](https://github.com/prismicio/prismic-gatsby/tree/main/docs) now rather than on the Prismic site.

**Comment by angeloashmore** [comment]
Hey everyone, `Proxy`s are necessary to support the content relationship `document` property during previews. You will see a `Proxy` object when `console.log()`ing a field, but the data within it is still there.

You can confirm this by logging properties of the object rather than the whole object. For example:

```ts
```

**Comment by kieranstartup** [comment]
Hey @angeloashmore,

Thanks for implementing this, I've just tested and it works perfectly. 

Really appreciate it!
