### ISSUE TITLE
Links to gatsby-source-prismic git repository are broken

### ISSUE THREAD

**Issue by faessler** [prismicio/prismic-gatsby#544]
### Description

Links on npmjs.com and gatsbyjs.com referencing to the git repository of the following plugins are broken (404):
- `gatsby-source-prismic`
- `gatsby-plugin-prismic-previews`

They point to an old repository.

#### Steps to reproduce
1. Go to
  a. https://www.npmjs.com/package/gatsby-source-prismic
  b. https://www.gatsbyjs.com/plugins/gatsby-source-prismic
3. Click on the "Repository" / "View plugin on GitHub" link

#### What is expected?

- It opens: https://github.com/prismicio/prismic-gatsby

#### What is actually happening?

- You get a 404, it opens: https://github.com/prismicio-community/prismic-gatsby-early-access

**Comment by laradevitt** [comment]
Can this be fixed? It's super annoying just trying to find the github repo.

**Comment by angeloashmore** [comment]
Thanks for the ping. This is fixed now:

- https://www.npmjs.com/package/gatsby-source-prismic
- https://www.npmjs.com/package/gatsby-plugin-prismic-previews
