### ISSUE TITLE
Possible to filter repeatables ?

### ISSUE THREAD

**Issue by Coriou** [prismicio/prismic-gatsby#60]
Very new to GraphQL (first time using it in fact), and I'm trying to do something that would really improve my build times, but seems impossible. I'd like to limit the items returned from a Prismic repeatable group.

Here's an example query (which does not work), to demonstrate what I'd like to do :

```graphql
query allProducts {
  allPrismicProduct {
    edges {
      node {
        data {
          side_images(first: 1) {
            side_image {
              localFile {
                ...
              }
            }
          }
        }
      }
    }
  }
}
```

Notice how I try to filter "side_images" which is a repeatable group of images in Prismic. I only care about the first item, and since I'm doing image transformation on them I'm basically wasting computation processing all of them when I only need one.

So, I'm not sure whether this is a limitation induced by GraphQL itself, or if it's just not implemented in the plugin. Sorry if the question is proper stupid, couldn't find a definitive answer myself.

What makes me think it's possible, is [this post](https://developer.github.com/v4/guides/resource-limitations/) in which you can see an example that does :

```graphql
query {
  viewer {
    login
    repositories(first: 100) {
      edges {
        node {
          id

          issues(first: 50) {
            edges {
              node {
                id

                labels(first: 60) {
                  edges {
                    node {
                      id
                      name
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

It looks like it's the same thing I'm trying to do.

**Comment by angeloashmore** [comment]
@Coriou So sorry there wasn't any response to your issue. I'm going through old issues and cleaning them out.

Filtering/limiting group fields is not possible in the Gatsby plugin, but you can use the Imgix image fields (`gatsbyImageData`, `fixed`, `fluid`) to do image transformations at request time. This will drastically reduce your development and build times.
