### ISSUE TITLE
 source and transform nodes never ends

### ISSUE THREAD

**Issue by RobinHerzog** [prismicio/prismic-gatsby#73]
Hi,

When the amount of image is too large,  source and transform nodes never ends even with a rapid internet connection.

Does anyone have a solution ?

**Comment by simplesessions** [comment]
@RobinHerzog whenever that happens, I've just quit out of it, then start it back up again and it seems to load.

**Comment by simplesessions** [comment]
@RobinHerzog Check out the just-published v2.2.0 that provides the ability to disable the downloading/processing of images. See https://github.com/angeloashmore/gatsby-source-prismic/pull/75 for more.

**Comment by abedziak** [comment]
Hey, I am also started having this problem and my source and transform nodes literally never ends. I even upgraded to a new version and am logging every node in shouldNormalizeImage, but it just stops and nothing happens. I don't know if this is an issue with a plugin or Prismic API as I can see documents being logged which no longer exist

**Comment by angeloashmore** [comment]
@abedziak Could you try clearing your `.cache` folder and rebuilding? I'm not sure why you would be logging old documents.

**Comment by stjepangolemac** [comment]
We have the same issue. Process just hangs, but it works if you restart it a couple of times.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues. If this is still a problem, please open a new issue and I can take a look! Thanks!
