### ISSUE TITLE
Gatsby Image Support for Integration Fields

### ISSUE THREAD

**Issue by foresttoney** [prismicio/prismic-gatsby#86]
Recently, Prismic launched support for a feature called `Integration Fields`. It allows a user to create a new Custom Prismic field from an external API (Shopify, Magento, etc).

A query against a Shopify Integration Field looks something like:

```
{
  prismicFooBook {
    uid
    data {
      book {
        body_html
        title
        image {
          src
        }
      }
    }
  }
}
```

Would it be within the scope of this library to add Gatsby Image support for `image`? If so, what kind of work would go into implementing and maintaining this feature?

**Comment by angeloashmore** [comment]
If the fields follow standard Prismic types, then yes, this is possible. I have not explored integration fields yet, but if you are able to, could you post a JSON custom type schema that utilizes integration fields?

**Comment by lgollut** [comment]
Hi @angeloashmore 

Here is a simple schema defining an Integration Field

```json
{
  "Main": {
    "sample_integration_field": {
      "type": "IntegrationFields",
      "config": {
        "catalog": "repository_name--field_name",
        "label": "Integration Field",
        "placeholder": "Sample integration field"
      }
    }
  }
}
```

Those fields are defined in the repository settings and `field_name` is provided there.

**Comment by angeloashmore** [comment]
@lgollut Saw your branch on the integrations fields. Thanks for giving it a try!

The main problem we have right now is not knowing which fields are available for an integration field. The schema from Prismic does not tell us what kind of integration catalog it uses (e.g. "Shopify", "Magento", "My Custom API"). As a result, we cannot build a GraphQL type for it.

- **Option 1**: Ignore integration fields and allow Gatsby to infer the shape. Cannot provide transformations like `gatsby-image`.
- **Option 2**: Allow users to provide their own type mappings (i.e. type path to GraphQL type). Still cannot provide transformations like `gatsby-image`. This seems like something Gatsby could provide on their own in the future so I am against this.
- **Options 3**: Utilize a transformer-like system that reads the nodes after creation where we can read the data within it. Then we can create a child node with transformations. Not a fully fleshed-out idea but this could work.

Option 2 could be something like the following:

```js
// gatsby-config.js

plugins: [
  {
    resolve: 'gatsby-source-prismic',
    options: {
      schemas: {
        // Schemas here
      },
      typePaths: {
        'page.data.product': 'ShopifyProduct'
      },
    }
  },
],
```

Where `ShopifyProduct` is defined in the site's `gatsby-node` file using `createTypes`.

**Comment by OllieJT** [comment]
I think this might be related to [#113](https://github.com/angeloashmore/gatsby-source-prismic/issues/113).

Is there any workaround currently implemented?

**Comment by Aaronkala** [comment]
Referencing @angeloashmore https://github.com/angeloashmore/gatsby-source-prismic/issues/113#issuecomment-609523539

> v3.0.0 falls back to JSON type for unknown fields, including integration fields. You will automatically get the full object without specifying subfields. This is not ideal, but it is currently the best way to support integration fields.

**Comment by angeloashmore** [comment]
I'm cleaning out old issues and closing this due to its age. If this is still an issue, please open a new issue and I can take a look!

Integration Fields are currently inferred by Gatsby since Prismic does not provide information about the data within the Integration Field. It is done this way because Integration Fields can return any kind of data which cannot be predicted.

If you know the shape of your data, you can use Gatsby's `createSchemaCustomization` to override the type of your Integration Fields' type. By overriding the type, you can provide a new field or augment an existing one to be a `File` node which will be transformed with `gatsby-transformer-sharp`.
